// Code generated by aidlgen. DO NOT EDIT.

package demo

import (
	"context"
	"fmt"
	"github.com/wdsgyj/libbinder-go/binder"
)

func ifooWriteNullableParcelFileDescriptorToParcel(p *binder.Parcel, v *binder.ParcelFileDescriptor) error {
	if v == nil {
		return p.WriteParcelFileDescriptor(binder.NewParcelFileDescriptor(-1))
	}
	return p.WriteParcelFileDescriptor(*v)
}

func ifooReadNullableParcelFileDescriptorFromParcel(p *binder.Parcel) (*binder.ParcelFileDescriptor, error) {
	v, err := p.ReadParcelFileDescriptor()
	if err != nil {
		return nil, err
	}
	if v.FD() < 0 {
		return nil, nil
	}
	return &v, nil
}

func ifooReadRequiredParcelFileDescriptorFromParcel(p *binder.Parcel) (binder.ParcelFileDescriptor, error) {
	v, err := p.ReadParcelFileDescriptor()
	if err != nil {
		return binder.ParcelFileDescriptor{}, err
	}
	if v.FD() < 0 {
		return binder.ParcelFileDescriptor{}, binder.ErrBadParcelable
	}
	return v, nil
}

const IFooDescriptor = "demo.IFoo"
const IFooA int32 = (1 << 0)
const IFooB int32 = (IFooA | (1 << 1))

type IFoo interface {
}

type iFooClient struct {
	target binder.Binder
}

func NewIFooClient(target binder.Binder) IFoo {
	if target == nil {
		return nil
	}
	return &iFooClient{target: target}
}

func (c *iFooClient) AsBinder() binder.Binder {
	if c == nil {
		return nil
	}
	return c.target
}

func writeIFooToParcel(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v IFoo) error {
	if v == nil {
		return p.WriteStrongBinder(nil)
	}
	if provider, ok := any(v).(binder.BinderProvider); ok {
		return p.WriteStrongBinder(provider.AsBinder())
	}
	if registrar == nil {
		return fmt.Errorf("%w: no local handler registrar available for IFoo", binder.ErrUnsupported)
	}
	b, err := registrar.RegisterLocalHandler(NewIFooHandlerWithRegistrar(registrar, v))
	if err != nil {
		return err
	}
	return p.WriteStrongBinder(b)
}

func readIFooFromParcel(p *binder.Parcel) (IFoo, error) {
	b, err := p.ReadStrongBinder()
	if err != nil {
		return nil, err
	}
	if b == nil {
		return nil, nil
	}
	return NewIFooClient(b), nil
}

type iFooHandler struct {
	impl      IFoo
	registrar binder.LocalHandlerRegistrar
}

func NewIFooHandler(impl IFoo) binder.Handler {
	return NewIFooHandlerWithRegistrar(nil, impl)
}

func NewIFooHandlerWithRegistrar(registrar binder.LocalHandlerRegistrar, impl IFoo) binder.Handler {
	return &iFooHandler{impl: impl, registrar: registrar}
}

func (h *iFooHandler) Descriptor() string {
	return IFooDescriptor
}

func (h *iFooHandler) HandleTransact(ctx context.Context, code uint32, data *binder.Parcel) (*binder.Parcel, error) {
	descriptor, err := data.ReadInterfaceToken()
	if err != nil {
		return nil, err
	}
	if descriptor != IFooDescriptor {
		return nil, fmt.Errorf("%w: descriptor %q, want %q", binder.ErrBadParcelable, descriptor, IFooDescriptor)
	}
	switch code {
	default:
		return nil, fmt.Errorf("%w: IFoo transaction code %d", binder.ErrUnknownTransaction, code)
	}
}

func CheckIFooService(ctx context.Context, sm binder.ServiceManager, name string) (IFoo, error) {
	service, err := sm.CheckService(ctx, name)
	if err != nil {
		return nil, err
	}
	return NewIFooClient(service), nil
}

func WaitIFooService(ctx context.Context, sm binder.ServiceManager, name string) (IFoo, error) {
	service, err := sm.WaitService(ctx, name)
	if err != nil {
		return nil, err
	}
	return NewIFooClient(service), nil
}

func AddIFooService(ctx context.Context, sm binder.ServiceManager, name string, impl IFoo, opts ...binder.AddServiceOption) error {
	if registrar, ok := sm.(binder.LocalHandlerRegistrar); ok {
		return sm.AddService(ctx, name, NewIFooHandlerWithRegistrar(registrar, impl), opts...)
	}
	return sm.AddService(ctx, name, NewIFooHandler(impl), opts...)
}
