// Code generated by aidlgen. DO NOT EDIT.

package generatedfixture

import (
	"context"
	"fmt"

	"github.com/wdsgyj/libbinder-go/binder"
)

func writeNullableParcelFileDescriptorToParcel(p *binder.Parcel, v *binder.ParcelFileDescriptor) error {
	if v == nil {
		return p.WriteParcelFileDescriptor(binder.NewParcelFileDescriptor(-1))
	}
	return p.WriteParcelFileDescriptor(*v)
}

func readNullableParcelFileDescriptorFromParcel(p *binder.Parcel) (*binder.ParcelFileDescriptor, error) {
	v, err := p.ReadParcelFileDescriptor()
	if err != nil {
		return nil, err
	}
	if v.FD() < 0 {
		return nil, nil
	}
	return &v, nil
}

func readRequiredParcelFileDescriptorFromParcel(p *binder.Parcel) (binder.ParcelFileDescriptor, error) {
	v, err := p.ReadParcelFileDescriptor()
	if err != nil {
		return binder.ParcelFileDescriptor{}, err
	}
	if v.FD() < 0 {
		return binder.ParcelFileDescriptor{}, binder.ErrBadParcelable
	}
	return v, nil
}

type Payload struct {
	Count int32
}

func writePayloadToParcel(p *binder.Parcel, v Payload) error {
	if err := p.WriteInt32(v.Count); err != nil {
		return err
	}
	return nil
}

func readPayloadFromParcel(p *binder.Parcel) (Payload, error) {
	var v Payload
	countValue, err := p.ReadInt32()
	if err != nil {
		return Payload{}, err
	}
	v.Count = countValue
	return v, nil
}

func writeNullablePayloadToParcel(p *binder.Parcel, v *Payload) error {
	if v == nil {
		return p.WriteInt32(0)
	}
	if err := p.WriteInt32(1); err != nil {
		return err
	}
	return writePayloadToParcel(p, *v)
}

func readNullablePayloadFromParcel(p *binder.Parcel) (*Payload, error) {
	present, err := p.ReadInt32()
	if err != nil {
		return nil, err
	}
	if present == 0 {
		return nil, nil
	}
	v, err := readPayloadFromParcel(p)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

const IEchoDescriptor = "generatedfixture.IEcho"
const IEchoTransactionEcho uint32 = 1

type IEcho interface {
	Echo(ctx context.Context, payload Payload) (Payload, error)
}

type iEchoClient struct {
	target binder.Binder
}

func NewIEchoClient(target binder.Binder) IEcho {
	if target == nil {
		return nil
	}
	return &iEchoClient{target: target}
}

func (c *iEchoClient) AsBinder() binder.Binder {
	if c == nil {
		return nil
	}
	return c.target
}

func writeIEchoToParcel(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v IEcho) error {
	if v == nil {
		return p.WriteStrongBinder(nil)
	}
	if provider, ok := any(v).(binder.BinderProvider); ok {
		return p.WriteStrongBinder(provider.AsBinder())
	}
	if registrar == nil {
		return fmt.Errorf("%w: no local handler registrar available for IEcho", binder.ErrUnsupported)
	}
	b, err := registrar.RegisterLocalHandler(NewIEchoHandlerWithRegistrar(registrar, v))
	if err != nil {
		return err
	}
	return p.WriteStrongBinder(b)
}

func readIEchoFromParcel(p *binder.Parcel) (IEcho, error) {
	b, err := p.ReadStrongBinder()
	if err != nil {
		return nil, err
	}
	if b == nil {
		return nil, nil
	}
	return NewIEchoClient(b), nil
}

func (c *iEchoClient) Echo(ctx context.Context, payload Payload) (Payload, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	data := binder.NewParcel()
	if err := data.WriteInterfaceToken(IEchoDescriptor); err != nil {
		return *new(Payload), err
	}
	if err := writePayloadToParcel(data, payload); err != nil {
		return *new(Payload), err
	}
	reply, err := c.target.Transact(ctx, IEchoTransactionEcho, data, binder.FlagNone)
	if err != nil {
		return *new(Payload), err
	}
	if reply == nil {
		return *new(Payload), binder.ErrBadParcelable
	}
	ret, err := readPayloadFromParcel(reply)
	if err != nil {
		return *new(Payload), err
	}
	return ret, nil
}

type iEchoHandler struct {
	impl      IEcho
	registrar binder.LocalHandlerRegistrar
}

func NewIEchoHandler(impl IEcho) binder.Handler {
	return NewIEchoHandlerWithRegistrar(nil, impl)
}

func NewIEchoHandlerWithRegistrar(registrar binder.LocalHandlerRegistrar, impl IEcho) binder.Handler {
	return &iEchoHandler{impl: impl, registrar: registrar}
}

func (h *iEchoHandler) Descriptor() string {
	return IEchoDescriptor
}

func (h *iEchoHandler) HandleTransact(ctx context.Context, code uint32, data *binder.Parcel) (*binder.Parcel, error) {
	descriptor, err := data.ReadInterfaceToken()
	if err != nil {
		return nil, err
	}
	if descriptor != IEchoDescriptor {
		return nil, fmt.Errorf("%w: descriptor %q, want %q", binder.ErrBadParcelable, descriptor, IEchoDescriptor)
	}
	switch code {
	case IEchoTransactionEcho:
		payload, err := readPayloadFromParcel(data)
		if err != nil {
			return nil, err
		}
		ret, err := h.impl.Echo(ctx, payload)
		if err != nil {
			return nil, err
		}
		reply := binder.NewParcel()
		if err := writePayloadToParcel(reply, ret); err != nil {
			return nil, err
		}
		return reply, nil
	default:
		return nil, fmt.Errorf("%w: IEcho transaction code %d", binder.ErrUnknownTransaction, code)
	}
}

func CheckIEchoService(ctx context.Context, sm binder.ServiceManager, name string) (IEcho, error) {
	service, err := sm.CheckService(ctx, name)
	if err != nil {
		return nil, err
	}
	return NewIEchoClient(service), nil
}

func WaitIEchoService(ctx context.Context, sm binder.ServiceManager, name string) (IEcho, error) {
	service, err := sm.WaitService(ctx, name)
	if err != nil {
		return nil, err
	}
	return NewIEchoClient(service), nil
}

func AddIEchoService(ctx context.Context, sm binder.ServiceManager, name string, impl IEcho, opts ...binder.AddServiceOption) error {
	if registrar, ok := sm.(binder.LocalHandlerRegistrar); ok {
		return sm.AddService(ctx, name, NewIEchoHandlerWithRegistrar(registrar, impl), opts...)
	}
	return sm.AddService(ctx, name, NewIEchoHandler(impl), opts...)
}
