// Code generated by aidlgen. DO NOT EDIT.

package demo

import (
	"github.com/wdsgyj/libbinder-go/binder"
)

func holderWriteNullableParcelFileDescriptorToParcel(p *binder.Parcel, v *binder.ParcelFileDescriptor) error {
	if v == nil {
		return p.WriteParcelFileDescriptor(binder.NewParcelFileDescriptor(-1))
	}
	return p.WriteParcelFileDescriptor(*v)
}

func holderReadNullableParcelFileDescriptorFromParcel(p *binder.Parcel) (*binder.ParcelFileDescriptor, error) {
	v, err := p.ReadParcelFileDescriptor()
	if err != nil {
		return nil, err
	}
	if v.FD() < 0 {
		return nil, nil
	}
	return &v, nil
}

func holderReadRequiredParcelFileDescriptorFromParcel(p *binder.Parcel) (binder.ParcelFileDescriptor, error) {
	v, err := p.ReadParcelFileDescriptor()
	if err != nil {
		return binder.ParcelFileDescriptor{}, err
	}
	if v.FD() < 0 {
		return binder.ParcelFileDescriptor{}, binder.ErrBadParcelable
	}
	return v, nil
}

type HolderKind int32

const (
	HolderKindOne HolderKind = 0
	HolderKindTwo HolderKind = 1
)

func writeHolderKindToParcel(p *binder.Parcel, v HolderKind) error {
	return p.WriteInt32(int32(v))
}

func readHolderKindFromParcel(p *binder.Parcel) (HolderKind, error) {
	v, err := p.ReadInt32()
	if err != nil {
		return 0, err
	}
	return HolderKind(v), nil
}

func WriteHolderKindToParcel(p *binder.Parcel, v HolderKind) error {
	return writeHolderKindToParcel(p, v)
}

func ReadHolderKindFromParcel(p *binder.Parcel) (HolderKind, error) {
	return readHolderKindFromParcel(p)
}

const (
	HolderMask int32 = (1 << 3)
)

type Holder struct {
	Kind HolderKind
}

func NewHolder() Holder {
	v := Holder{}
	v.Kind = HolderKindTwo
	return v
}

func writeHolderToParcel(p *binder.Parcel, v Holder) error {
	if err := writeHolderKindToParcel(p, v.Kind); err != nil {
		return err
	}
	return nil
}

func readHolderFromParcel(p *binder.Parcel) (Holder, error) {
	v := NewHolder()
	kindValue, err := readHolderKindFromParcel(p)
	if err != nil {
		return Holder{}, err
	}
	v.Kind = kindValue
	return v, nil
}

func writeNullableHolderToParcel(p *binder.Parcel, v *Holder) error {
	if v == nil {
		return p.WriteInt32(0)
	}
	if err := p.WriteInt32(1); err != nil {
		return err
	}
	return writeHolderToParcel(p, *v)
}

func readNullableHolderFromParcel(p *binder.Parcel) (*Holder, error) {
	present, err := p.ReadInt32()
	if err != nil {
		return nil, err
	}
	if present == 0 {
		return nil, nil
	}
	v, err := readHolderFromParcel(p)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

func WriteHolderToParcel(p *binder.Parcel, v Holder) error {
	return writeHolderToParcel(p, v)
}

func WriteHolderToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v Holder) error {
	return writeHolderToParcel(p, v)
}

func ReadHolderFromParcel(p *binder.Parcel) (Holder, error) {
	return readHolderFromParcel(p)
}

func WriteNullableHolderToParcel(p *binder.Parcel, v *Holder) error {
	return writeNullableHolderToParcel(p, v)
}

func WriteNullableHolderToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v *Holder) error {
	return writeNullableHolderToParcel(p, v)
}

func ReadNullableHolderFromParcel(p *binder.Parcel) (*Holder, error) {
	return readNullableHolderFromParcel(p)
}
