package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"path/filepath"
	"sort"
	"strings"

	"github.com/wdsgyj/libbinder-go/internal/aidl/gomodel"
)

const defaultRuntimeImport = "github.com/wdsgyj/libbinder-go/binder"

type GoOptions struct {
	RuntimeImportPath   string
	TypeMappingsPath    string
	CustomParcelables   map[string]gomodel.CustomParcelableConfig
	GeneratedImportRoot string
}

type OutputFile struct {
	Path    string
	Content []byte
}

func RenderGo(model *gomodel.File, opts GoOptions) ([]OutputFile, error) {
	if model == nil {
		return nil, fmt.Errorf("nil model")
	}
	if len(model.ExternalRefs) != 0 {
		return nil, fmt.Errorf("unresolved external references: %s", strings.Join(model.ExternalRefs, ", "))
	}

	renderer := &goRenderer{
		model:               model,
		runtimeImportPath:   opts.RuntimeImportPath,
		typeMappingsPath:    opts.TypeMappingsPath,
		customParcelables:   opts.CustomParcelables,
		generatedImportRoot: opts.GeneratedImportRoot,
	}
	if renderer.runtimeImportPath == "" {
		renderer.runtimeImportPath = defaultRuntimeImport
	}
	renderer.indexModel()
	if err := renderer.validate(); err != nil {
		return nil, err
	}

	content, err := renderer.render()
	if err != nil {
		return nil, err
	}

	return []OutputFile{{
		Path:    outputPath(model),
		Content: content,
	}}, nil
}

type goRenderer struct {
	model               *gomodel.File
	runtimeImportPath   string
	typeMappingsPath    string
	customParcelables   map[string]gomodel.CustomParcelableConfig
	generatedImportRoot string
	buf                 bytes.Buffer
	parcelablesByName   map[string]*gomodel.Parcelable
	unionsByName        map[string]*gomodel.Union
}

type importSpec struct {
	Path  string
	Alias string
}

func (r *goRenderer) indexModel() {
	r.parcelablesByName = make(map[string]*gomodel.Parcelable, len(r.model.Parcelables))
	for _, p := range r.model.Parcelables {
		r.parcelablesByName[p.GoName] = p
	}
	r.unionsByName = make(map[string]*gomodel.Union, len(r.model.Unions))
	for _, u := range r.model.Unions {
		r.unionsByName[u.GoName] = u
	}
}

func (r *goRenderer) render() ([]byte, error) {
	r.linef("// Code generated by aidlgen. DO NOT EDIT.")
	r.linef("")
	r.linef("package %s", r.model.GoPackage)
	r.linef("")

	imports := r.imports()
	if len(imports) != 0 {
		r.linef("import (")
		for _, imp := range imports {
			if imp.Alias != "" {
				r.linef("\t%s %q", imp.Alias, imp.Path)
				continue
			}
			r.linef("\t%q", imp.Path)
		}
		r.linef(")")
		r.linef("")
	}

	r.renderParcelFileDescriptorHelpers()
	for _, enum := range r.model.Enums {
		r.renderEnum(enum)
	}
	for _, parcelable := range r.model.Parcelables {
		r.renderParcelable(parcelable)
	}
	for _, union := range r.model.Unions {
		r.renderUnion(union)
	}
	for _, iface := range r.model.Interfaces {
		r.renderInterface(iface)
	}

	out, err := format.Source(r.buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w\n%s", err, r.buf.String())
	}
	return out, nil
}

func (r *goRenderer) validate() error {
	for _, p := range r.model.Parcelables {
		if !p.Structured {
			continue
		}
		for _, c := range p.Consts {
			if err := r.validateConstType(c.Type); err != nil {
				return fmt.Errorf("parcelable %s const %s: %w", p.GoName, c.GoName, err)
			}
		}
		for _, field := range p.Fields {
			if err := r.validateTypeUsage(field.Type, false); err != nil {
				return fmt.Errorf("parcelable %s field %s: %w", p.GoName, field.GoName, err)
			}
		}
	}
	for _, u := range r.model.Unions {
		for _, field := range u.Fields {
			if err := r.validateTypeUsage(field.Type, false); err != nil {
				return fmt.Errorf("union %s field %s: %w", u.GoName, field.GoName, err)
			}
		}
	}
	for _, iface := range r.model.Interfaces {
		if iface.Stable && (iface.Version <= 0 || iface.Hash == "") {
			if r.typeMappingsPath != "" {
				return fmt.Errorf("stable interface %s missing version/hash mapping in %s", iface.AIDLName, r.typeMappingsPath)
			}
			return fmt.Errorf("stable interface %s missing version/hash mapping", iface.AIDLName)
		}
		for _, c := range iface.Consts {
			if err := r.validateConstType(c.Type); err != nil {
				return fmt.Errorf("interface %s const %s: %w", iface.GoName, c.GoName, err)
			}
		}
		for _, method := range iface.Methods {
			if method.Return != nil {
				if err := r.validateTypeUsage(method.Return.Type, true); err != nil {
					return fmt.Errorf("method %s.%s return: %w", iface.GoName, method.GoName, err)
				}
			}
			for _, arg := range method.Inputs {
				if err := r.validateTypeUsage(arg.Type, true); err != nil {
					return fmt.Errorf("method %s.%s input %s: %w", iface.GoName, method.GoName, arg.GoName, err)
				}
			}
			for _, arg := range method.Outputs {
				if err := r.validateTypeUsage(arg.Type, true); err != nil {
					return fmt.Errorf("method %s.%s output %s: %w", iface.GoName, method.GoName, arg.GoName, err)
				}
			}
		}
	}
	if r.generatedImportRoot == "" && r.requiresGeneratedImports() {
		return fmt.Errorf("cross-package AIDL references require generated import root")
	}
	return nil
}

func (r *goRenderer) validateConstType(typ *gomodel.Type) error {
	if typ == nil {
		return fmt.Errorf("nil type")
	}
	switch typ.Kind {
	case gomodel.TypeBool, gomodel.TypeByte, gomodel.TypeChar, gomodel.TypeInt32, gomodel.TypeInt64, gomodel.TypeFloat32, gomodel.TypeFloat64, gomodel.TypeString, gomodel.TypeEnum:
		return nil
	default:
		return fmt.Errorf("unsupported const type %s", typ.GoExpr)
	}
}

func (r *goRenderer) validateTypeUsage(typ *gomodel.Type, allowBinderObjects bool) error {
	if typ == nil {
		return fmt.Errorf("nil type")
	}
	switch typ.Kind {
	case gomodel.TypeVoid, gomodel.TypeBool, gomodel.TypeByte, gomodel.TypeChar, gomodel.TypeInt32, gomodel.TypeInt64, gomodel.TypeFloat32, gomodel.TypeFloat64, gomodel.TypeString, gomodel.TypeParcelable, gomodel.TypeEnum, gomodel.TypeUnion:
		return nil
	case gomodel.TypeFileDescriptor, gomodel.TypeParcelFileDescriptor:
		return nil
	case gomodel.TypeSlice, gomodel.TypeArray:
		return r.validateTypeUsage(typ.Elem, allowBinderObjects)
	case gomodel.TypeMap:
		if typ.Key == nil || typ.Value == nil {
			return fmt.Errorf("map type %q is missing key/value type", typ.GoExpr)
		}
		if typ.GoExpr == "map[any]any" {
			return nil
		}
		if !r.isValidMapKeyType(typ.Key) {
			return fmt.Errorf("unsupported map key type %q", r.typeExpr(typ.Key))
		}
		if err := r.validateTypeUsage(typ.Key, allowBinderObjects); err != nil {
			return err
		}
		return r.validateTypeUsage(typ.Value, allowBinderObjects)
	case gomodel.TypeInterface, gomodel.TypeBinder:
		return nil
	case gomodel.TypeExternal:
		return fmt.Errorf("external type %q is not implemented yet", typ.AIDLName)
	default:
		return fmt.Errorf("unsupported type %q", typ.GoExpr)
	}
}

func (r *goRenderer) imports() []importSpec {
	set := map[string]importSpec{}
	add := func(path string, alias string) {
		key := alias + "\x00" + path
		set[key] = importSpec{Path: path, Alias: alias}
	}

	add(r.runtimeImportPath, "")
	if len(r.model.Interfaces) != 0 {
		add("context", "")
	}
	if r.needsFmtImport() {
		add("fmt", "")
	}
	if r.hasStableInterfaces() {
		add("errors", "")
		add("sync", "")
	}
	for _, p := range r.model.Parcelables {
		if p.Custom == nil {
			continue
		}
		add(p.Custom.GoPackage, p.Custom.ImportAlias)
	}
	for _, p := range r.model.Parcelables {
		for _, field := range p.Fields {
			r.addTypeImports(set, field.Type)
		}
	}
	for _, u := range r.model.Unions {
		for _, field := range u.Fields {
			r.addTypeImports(set, field.Type)
		}
	}
	for _, iface := range r.model.Interfaces {
		for _, method := range iface.Methods {
			if method.Return != nil {
				r.addTypeImports(set, method.Return.Type)
			}
			for _, arg := range method.Inputs {
				r.addTypeImports(set, arg.Type)
			}
			for _, arg := range method.Outputs {
				r.addTypeImports(set, arg.Type)
			}
		}
	}

	imports := make([]importSpec, 0, len(set))
	for _, imp := range set {
		imports = append(imports, imp)
	}
	sort.Slice(imports, func(i, j int) bool {
		if imports[i].Path == imports[j].Path {
			return imports[i].Alias < imports[j].Alias
		}
		return imports[i].Path < imports[j].Path
	})
	return imports
}

func (r *goRenderer) needsFmtImport() bool {
	if len(r.model.Interfaces) != 0 || len(r.model.Unions) != 0 {
		return true
	}
	for _, p := range r.model.Parcelables {
		if p.Custom == nil {
			return true
		}
	}
	return false
}

func (r *goRenderer) addTypeImports(set map[string]importSpec, typ *gomodel.Type) {
	if typ == nil {
		return
	}
	switch typ.Kind {
	case gomodel.TypeSlice, gomodel.TypeArray:
		r.addTypeImports(set, typ.Elem)
	case gomodel.TypeMap:
		r.addTypeImports(set, typ.Key)
		r.addTypeImports(set, typ.Value)
	case gomodel.TypeParcelable:
		if cfg, ok := r.customParcelables[typ.AIDLName]; ok && cfg.GoPackage != "" {
			alias := customImportAlias(cfg.GoPackage)
			set[alias+"\x00"+cfg.GoPackage] = importSpec{Path: cfg.GoPackage, Alias: alias}
			return
		}
		if path, alias, ok := r.generatedImportSpec(typ); ok {
			set[alias+"\x00"+path] = importSpec{Path: path, Alias: alias}
		}
	case gomodel.TypeEnum, gomodel.TypeUnion, gomodel.TypeInterface:
		if path, alias, ok := r.generatedImportSpec(typ); ok {
			set[alias+"\x00"+path] = importSpec{Path: path, Alias: alias}
		}
	case gomodel.TypeBinder, gomodel.TypeExternal:
		return
	}
}

func customImportAlias(goPackage string) string {
	goPackage = strings.TrimSuffix(goPackage, "/")
	parts := strings.Split(goPackage, "/")
	var base string
	switch len(parts) {
	case 0:
		base = "customparcelable"
	case 1:
		base = parts[0]
	default:
		base = parts[len(parts)-2] + "_" + parts[len(parts)-1]
	}

	var b strings.Builder
	for _, r := range strings.ToLower(base) {
		switch {
		case 'a' <= r && r <= 'z', '0' <= r && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	alias := b.String()
	if alias == "" {
		return "customparcelable"
	}
	if alias[0] >= '0' && alias[0] <= '9' {
		return "aidl_" + alias
	}
	return alias
}

func aidlImportAlias(aidlPackage string) string {
	alias := sanitizeImportAliasName(strings.ReplaceAll(aidlPackage, ".", "_"))
	if alias == "" {
		return "aidl_generated"
	}
	return "aidl_" + alias
}

func sanitizeImportAliasName(name string) string {
	name = strings.ToLower(name)
	name = sanitizeIdentifier(name)
	if name == "" {
		return "aidl"
	}
	if token.Lookup(name).IsKeyword() {
		name += "_aidl"
	}
	if name[0] >= '0' && name[0] <= '9' {
		name = "aidl_" + name
	}
	return name
}

func (r *goRenderer) generatedImportSpec(typ *gomodel.Type) (string, string, bool) {
	if typ == nil || typ.DeclPackage == "" || typ.DeclPackage == r.model.AIDLPackage || r.generatedImportRoot == "" {
		return "", "", false
	}
	path := strings.TrimSuffix(r.generatedImportRoot, "/") + "/" + filepath.ToSlash(generatedPackageDir(typ.DeclPackage))
	return path, aidlImportAlias(typ.DeclPackage), true
}

func (r *goRenderer) requiresGeneratedImports() bool {
	var check func(typ *gomodel.Type) bool
	check = func(typ *gomodel.Type) bool {
		if typ == nil {
			return false
		}
		switch typ.Kind {
		case gomodel.TypeSlice, gomodel.TypeArray:
			return check(typ.Elem)
		case gomodel.TypeMap:
			return check(typ.Key) || check(typ.Value)
		case gomodel.TypeParcelable, gomodel.TypeEnum, gomodel.TypeUnion, gomodel.TypeInterface:
			if _, _, ok := r.customParcelableConfig(typ); ok {
				return false
			}
			return typ.DeclPackage != "" && typ.DeclPackage != r.model.AIDLPackage
		default:
			return false
		}
	}
	for _, p := range r.model.Parcelables {
		for _, field := range p.Fields {
			if check(field.Type) {
				return true
			}
		}
	}
	for _, u := range r.model.Unions {
		for _, field := range u.Fields {
			if check(field.Type) {
				return true
			}
		}
	}
	for _, iface := range r.model.Interfaces {
		for _, c := range iface.Consts {
			if check(c.Type) {
				return true
			}
		}
		for _, method := range iface.Methods {
			if method.Return != nil && check(method.Return.Type) {
				return true
			}
			for _, arg := range method.Inputs {
				if check(arg.Type) {
					return true
				}
			}
			for _, arg := range method.Outputs {
				if check(arg.Type) {
					return true
				}
			}
		}
	}
	return false
}

func (r *goRenderer) hasStableInterfaces() bool {
	for _, iface := range r.model.Interfaces {
		if iface.Stable {
			return true
		}
	}
	return false
}

func outputPath(model *gomodel.File) string {
	dir := "."
	if model.AIDLPackage != "" {
		dir = generatedPackageDir(model.AIDLPackage)
	} else if model.SourcePath != "" {
		parent := filepath.Base(filepath.Dir(model.SourcePath))
		if parent != "" && parent != "." && parent != string(filepath.Separator) {
			dir = model.GoPackage
		}
	}
	base := "aidl_generated"
	if model.SourcePath != "" {
		base = strings.TrimSuffix(filepath.Base(model.SourcePath), filepath.Ext(model.SourcePath))
	}
	base = strings.ToLower(base) + "_aidl.go"
	return filepath.Join(dir, base)
}

func generatedPackageDir(aidlPackage string) string {
	if aidlPackage == "" {
		return ""
	}
	parts := strings.Split(aidlPackage, ".")
	for i, part := range parts {
		if part == "internal" {
			parts[i] = "internal_"
		}
	}
	return filepath.Join(parts...)
}

func (r *goRenderer) typeExpr(typ *gomodel.Type) string {
	if typ == nil {
		return ""
	}
	switch typ.Kind {
	case gomodel.TypeSlice:
		return "[]" + r.typeExpr(typ.Elem)
	case gomodel.TypeArray:
		return "[]" + r.typeExpr(typ.Elem)
	case gomodel.TypeMap:
		if typ.Key == nil || typ.Value == nil {
			return "map[any]any"
		}
		return fmt.Sprintf("map[%s]%s", r.typeExpr(typ.Key), r.typeExpr(typ.Value))
	case gomodel.TypeParcelable:
		if cfg, alias, ok := r.customParcelableConfig(typ); ok {
			name := alias + "." + cfg.GoType
			if typ.Nullable {
				return "*" + name
			}
			return name
		}
		return r.namedTypeExpr(typ)
	case gomodel.TypeEnum, gomodel.TypeUnion, gomodel.TypeInterface:
		return r.namedTypeExpr(typ)
	default:
		return typ.GoExpr
	}
}

func (r *goRenderer) namedTypeExpr(typ *gomodel.Type) string {
	if typ == nil {
		return ""
	}
	if typ.NamedGo == "" {
		return typ.GoExpr
	}
	name := typ.NamedGo
	if qualifier := r.generatedQualifier(typ); qualifier != "" {
		name = qualifier + name
	}
	if typ.Nullable && (typ.Kind == gomodel.TypeParcelable || typ.Kind == gomodel.TypeUnion) {
		return "*" + name
	}
	return name
}

func (r *goRenderer) generatedQualifier(typ *gomodel.Type) string {
	if _, alias, ok := r.generatedImportSpec(typ); ok {
		return alias + "."
	}
	return ""
}

func (r *goRenderer) zeroExpr(typ *gomodel.Type) string {
	if typ == nil {
		return "nil"
	}
	switch typ.Kind {
	case gomodel.TypeBool:
		return "false"
	case gomodel.TypeByte, gomodel.TypeChar, gomodel.TypeInt32, gomodel.TypeInt64, gomodel.TypeFloat32, gomodel.TypeFloat64, gomodel.TypeEnum:
		return fmt.Sprintf("%s(0)", r.typeExpr(typ))
	case gomodel.TypeString:
		if typ.Nullable {
			return "nil"
		}
		return `""`
	case gomodel.TypeFileDescriptor:
		return "binder.FileDescriptor{}"
	case gomodel.TypeParcelFileDescriptor:
		if typ.Nullable {
			return "nil"
		}
		return "binder.ParcelFileDescriptor{}"
	case gomodel.TypeParcelable, gomodel.TypeUnion:
		if typ.Nullable {
			return "nil"
		}
		return "*new(" + r.typeExpr(typ) + ")"
	case gomodel.TypeSlice, gomodel.TypeArray:
		return "nil"
	case gomodel.TypeMap:
		return "nil"
	case gomodel.TypeInterface, gomodel.TypeBinder:
		return "nil"
	default:
		if typ.Nullable {
			return "nil"
		}
		if r.typeExpr(typ) == "" {
			return "nil"
		}
		return r.typeExpr(typ) + "{}"
	}
}

func (r *goRenderer) isRawMapType(typ *gomodel.Type) bool {
	return typ != nil && typ.Kind == gomodel.TypeMap && typ.GoExpr == "map[any]any"
}

func (r *goRenderer) isValidMapKeyType(typ *gomodel.Type) bool {
	if typ == nil {
		return false
	}
	switch typ.Kind {
	case gomodel.TypeBool, gomodel.TypeByte, gomodel.TypeChar, gomodel.TypeInt32, gomodel.TypeInt64, gomodel.TypeFloat32, gomodel.TypeFloat64, gomodel.TypeString, gomodel.TypeEnum, gomodel.TypeBinder, gomodel.TypeInterface:
		return true
	default:
		return false
	}
}

func (r *goRenderer) nonNullableType(typ *gomodel.Type) *gomodel.Type {
	if typ == nil {
		return nil
	}
	copy := *typ
	copy.Nullable = false
	return &copy
}

func (r *goRenderer) dynamicWriteExpr(parcel string, value string, typ *gomodel.Type, registrar string) string {
	if typ == nil {
		return `fmt.Errorf("%w: nil dynamic type", binder.ErrBadParcelable)`
	}
	switch typ.Kind {
	case gomodel.TypeBool:
		return r.dynamicTaggedWriteExpr(parcel, "binder.ValueBoolean", fmt.Sprintf("%s.WriteBool(%s)", parcel, value))
	case gomodel.TypeByte:
		return r.dynamicTaggedWriteExpr(parcel, "binder.ValueByte", fmt.Sprintf("%s.WriteInt32(int32(%s))", parcel, value))
	case gomodel.TypeChar:
		return r.dynamicTaggedWriteExpr(parcel, "binder.ValueChar", fmt.Sprintf("%s.WriteInt32(int32(%s))", parcel, value))
	case gomodel.TypeInt32:
		return r.dynamicTaggedWriteExpr(parcel, "binder.ValueInteger", fmt.Sprintf("%s.WriteInt32(%s)", parcel, value))
	case gomodel.TypeInt64:
		return r.dynamicTaggedWriteExpr(parcel, "binder.ValueLong", fmt.Sprintf("%s.WriteInt64(%s)", parcel, value))
	case gomodel.TypeFloat32:
		return r.dynamicTaggedWriteExpr(parcel, "binder.ValueFloat", fmt.Sprintf("%s.WriteFloat32(%s)", parcel, value))
	case gomodel.TypeFloat64:
		return r.dynamicTaggedWriteExpr(parcel, "binder.ValueDouble", fmt.Sprintf("%s.WriteFloat64(%s)", parcel, value))
	case gomodel.TypeString:
		if typ.Nullable {
			return fmt.Sprintf(`func() error {
	if %s == nil {
		return %s.WriteInt32(int32(binder.ValueNull))
	}
	if err := %s.WriteInt32(int32(binder.ValueString)); err != nil {
		return err
	}
	return %s.WriteString(*%s)
}()`, value, parcel, parcel, parcel, value)
		}
		return r.dynamicTaggedWriteExpr(parcel, "binder.ValueString", fmt.Sprintf("%s.WriteString(%s)", parcel, value))
	case gomodel.TypeEnum:
		return r.dynamicTaggedWriteExpr(parcel, "binder.ValueInteger", r.writeExpr(parcel, value, typ, registrar))
	case gomodel.TypeParcelable, gomodel.TypeUnion:
		base := r.nonNullableType(typ)
		payloadValue := value
		nullCheck := ""
		nullReturn := ""
		if typ.Nullable {
			payloadValue = "*" + value
			nullCheck = fmt.Sprintf("if %s == nil {\n\t\treturn %s.WriteInt32(int32(binder.ValueNull))\n\t}\n\t", value, parcel)
		}
		nullReturn = fmt.Sprintf(`func() error {
	%sif err := %s.WriteInt32(int32(binder.ValueParcelable)); err != nil {
		return err
	}
	if err := %s.WriteString(%q); err != nil {
		return err
	}
	return %s
}()`, nullCheck, parcel, parcel, typ.AIDLName, r.writeExpr(parcel, payloadValue, base, registrar))
		return nullReturn
	case gomodel.TypeBinder, gomodel.TypeInterface:
		return fmt.Sprintf(`func() error {
	if %s == nil {
		return %s.WriteInt32(int32(binder.ValueNull))
	}
	if err := %s.WriteInt32(int32(binder.ValueIBinder)); err != nil {
		return err
	}
	return %s
}()`, value, parcel, parcel, r.writeExpr(parcel, value, typ, registrar))
	case gomodel.TypeMap:
		return fmt.Sprintf(`func() error {
	if %s == nil {
		return %s.WriteInt32(int32(binder.ValueNull))
	}
	if err := %s.WriteInt32(int32(binder.ValueMap)); err != nil {
		return err
	}
	return %s
}()`, value, parcel, parcel, r.writeExpr(parcel, value, typ, registrar))
	case gomodel.TypeSlice:
		if !typ.IsList {
			return fmt.Sprintf(`fmt.Errorf("%%w: dynamic arrays are not implemented for %s", binder.ErrUnsupported)`, r.typeExpr(typ))
		}
		return fmt.Sprintf(`func() error {
	if %s == nil {
		return %s.WriteInt32(int32(binder.ValueNull))
	}
	if err := %s.WriteInt32(int32(binder.ValueList)); err != nil {
		return err
	}
	return binder.WriteSlice(%s, %s, func(p *binder.Parcel, item %s) error { return %s })
}()`, value, parcel, parcel, parcel, value, r.typeExpr(typ.Elem), r.dynamicWriteExpr("p", "item", typ.Elem, registrar))
	default:
		return fmt.Sprintf(`fmt.Errorf("%%w: unsupported dynamic type %s", binder.ErrUnsupported)`, r.typeExpr(typ))
	}
}

func (r *goRenderer) dynamicReadExpr(parcel string, typ *gomodel.Type) string {
	if typ == nil {
		return `func() (any, error) { return nil, binder.ErrBadParcelable }()`
	}
	switch typ.Kind {
	case gomodel.TypeBool:
		return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueBoolean", fmt.Sprintf("%s.ReadBool()", parcel), false, "")
	case gomodel.TypeByte:
		return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueByte", fmt.Sprintf(`func() (%s, error) {
	value, err := %s.ReadInt32()
	return %s(value), err
}()`, r.typeExpr(typ), parcel, r.typeExpr(typ)), false, "")
	case gomodel.TypeChar:
		return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueChar", fmt.Sprintf(`func() (%s, error) {
	value, err := %s.ReadInt32()
	return %s(value), err
}()`, r.typeExpr(typ), parcel, r.typeExpr(typ)), false, "")
	case gomodel.TypeInt32:
		return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueInteger", fmt.Sprintf("%s.ReadInt32()", parcel), false, "")
	case gomodel.TypeInt64:
		return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueLong", fmt.Sprintf("%s.ReadInt64()", parcel), false, "")
	case gomodel.TypeFloat32:
		return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueFloat", fmt.Sprintf("%s.ReadFloat32()", parcel), false, "")
	case gomodel.TypeFloat64:
		return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueDouble", fmt.Sprintf("%s.ReadFloat64()", parcel), false, "")
	case gomodel.TypeString:
		body := fmt.Sprintf("%s.ReadString()", parcel)
		if typ.Nullable {
			body = fmt.Sprintf(`func() (*string, error) {
	value, err := %s.ReadString()
	if err != nil {
		return nil, err
	}
	return &value, nil
}()`, parcel)
			return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueString", body, true, "nil")
		}
		return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueString", body, false, "")
	case gomodel.TypeEnum:
		return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueInteger", r.readExpr(parcel, typ), false, "")
	case gomodel.TypeParcelable, gomodel.TypeUnion:
		base := r.nonNullableType(typ)
		body := r.readExpr(parcel, base)
		if typ.Nullable {
			body = fmt.Sprintf(`func() (*%s, error) {
	if _, err := %s.ReadString(); err != nil {
		return nil, err
	}
	value, err := %s
	if err != nil {
		return nil, err
	}
	return &value, nil
}()`, r.typeExpr(base), parcel, body)
			return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueParcelable", body, true, "nil")
		}
		body = fmt.Sprintf(`func() (%s, error) {
	if _, err := %s.ReadString(); err != nil {
		return %s, err
	}
	return %s
}()`, r.typeExpr(base), parcel, r.zeroExpr(base), body)
		return r.dynamicReadTaggedExpr(parcel, base, "binder.ValueParcelable", body, false, "")
	case gomodel.TypeBinder, gomodel.TypeInterface:
		return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueIBinder", r.readExpr(parcel, typ), true, "nil")
	case gomodel.TypeMap:
		return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueMap", r.readExpr(parcel, typ), true, "nil")
	case gomodel.TypeSlice:
		if !typ.IsList {
			return fmt.Sprintf(`func() (%s, error) { return %s, fmt.Errorf("%%w: dynamic arrays are not implemented for %s", binder.ErrUnsupported) }()`, r.typeExpr(typ), r.zeroExpr(typ), r.typeExpr(typ))
		}
		body := fmt.Sprintf("binder.ReadSlice(%s, func(p *binder.Parcel) (%s, error) { return %s })", parcel, r.typeExpr(typ.Elem), r.dynamicReadExpr("p", typ.Elem))
		return r.dynamicReadTaggedExpr(parcel, typ, "binder.ValueList", body, true, "nil")
	default:
		return fmt.Sprintf(`func() (%s, error) { return %s, fmt.Errorf("%%w: unsupported dynamic type %s", binder.ErrUnsupported) }()`, r.typeExpr(typ), r.zeroExpr(typ), r.typeExpr(typ))
	}
}

func (r *goRenderer) dynamicTaggedWriteExpr(parcel string, tag string, body string) string {
	return fmt.Sprintf(`func() error {
	if err := %s.WriteInt32(int32(%s)); err != nil {
		return err
	}
	return %s
}()`, parcel, tag, body)
}

func (r *goRenderer) dynamicReadTaggedExpr(parcel string, typ *gomodel.Type, tag string, body string, allowNull bool, nullValue string) string {
	if typ == nil {
		return `func() (any, error) { return nil, binder.ErrBadParcelable }()`
	}
	if nullValue == "" {
		nullValue = r.zeroExpr(typ)
	}
	nullCase := ""
	if allowNull {
		nullCase = fmt.Sprintf("case binder.ValueNull:\n\t\treturn %s, nil\n\t", nullValue)
	}
	return fmt.Sprintf(`func() (%s, error) {
	tagValue, err := %s.ReadInt32()
	if err != nil {
		return %s, err
	}
	switch binder.ValueTag(tagValue) {
	case %s:
		return %s
	%sdefault:
		return %s, fmt.Errorf("%%w: unexpected value tag %%d for %s", binder.ErrBadParcelable, tagValue)
	}
}()`, r.typeExpr(typ), parcel, r.zeroExpr(typ), tag, body, nullCase, r.zeroExpr(typ), r.typeExpr(typ))
}

func (r *goRenderer) renderEnum(enum *gomodel.Enum) {
	r.linef("type %s %s", enum.GoName, r.typeExpr(enum.Underlying))
	r.linef("")
	r.linef("const (")
	for _, member := range enum.Members {
		valueExpr := member.Value
		if valueExpr == "" {
			valueExpr = "0"
		}
		r.linef("\t%s %s = %s", member.GoName, enum.GoName, valueExpr)
	}
	r.linef(")")
	r.linef("")
	r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", enum.GoName, enum.GoName)
	r.linef("\treturn %s", r.writeExpr("p", enumCastValue(enum), enumTypeAsBacking(enum), ""))
	r.linef("}")
	r.linef("")
	r.linef("func read%sFromParcel(p *binder.Parcel) (%s, error) {", enum.GoName, enum.GoName)
	r.linef("\tv, err := %s", r.readExpr("p", enumTypeAsBacking(enum)))
	r.linef("\tif err != nil {")
	r.linef("\t\treturn 0, err")
	r.linef("\t}")
	r.linef("\treturn %s(v), nil", enum.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func Write%sToParcel(p *binder.Parcel, v %s) error {", enum.GoName, enum.GoName)
	r.linef("\treturn write%sToParcel(p, v)", enum.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func Read%sFromParcel(p *binder.Parcel) (%s, error) {", enum.GoName, enum.GoName)
	r.linef("\treturn read%sFromParcel(p)", enum.GoName)
	r.linef("}")
	r.linef("")
}

func enumTypeAsBacking(enum *gomodel.Enum) *gomodel.Type {
	return &gomodel.Type{
		Kind:      enum.Underlying.Kind,
		AIDLName:  enum.Underlying.AIDLName,
		GoExpr:    enum.Underlying.GoExpr,
		IsBuiltin: enum.Underlying.IsBuiltin,
	}
}

func enumCastValue(enum *gomodel.Enum) string {
	if enum == nil || enum.Underlying == nil {
		return "v"
	}
	return fmt.Sprintf("%s(v)", enum.Underlying.GoExpr)
}

func (r *goRenderer) renderParcelFileDescriptorHelpers() {
	r.linef("func %s(p *binder.Parcel, v *binder.ParcelFileDescriptor) error {", r.nullableParcelFileDescriptorWriterName())
	r.linef("\tif v == nil {")
	r.linef("\t\treturn p.WriteInt32(0)")
	r.linef("\t}")
	r.linef("\tif err := p.WriteInt32(1); err != nil {")
	r.linef("\t\treturn err")
	r.linef("\t}")
	r.linef("\treturn p.WriteParcelFileDescriptor(*v)")
	r.linef("}")
	r.linef("")
	r.linef("func %s(p *binder.Parcel) (*binder.ParcelFileDescriptor, error) {", r.nullableParcelFileDescriptorReaderName())
	r.linef("\tpresent, err := p.ReadInt32()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif present == 0 {")
	r.linef("\t\treturn nil, nil")
	r.linef("\t}")
	r.linef("\tv, err := p.ReadParcelFileDescriptor()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\treturn &v, nil")
	r.linef("}")
	r.linef("")
	r.linef("func %s(p *binder.Parcel) (binder.ParcelFileDescriptor, error) {", r.requiredParcelFileDescriptorReaderName())
	r.linef("\tv, err := p.ReadParcelFileDescriptor()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn binder.ParcelFileDescriptor{}, err")
	r.linef("\t}")
	r.linef("\tif v.FD() < 0 {")
	r.linef("\t\treturn binder.ParcelFileDescriptor{}, binder.ErrBadParcelable")
	r.linef("\t}")
	r.linef("\treturn v, nil")
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderParcelable(p *gomodel.Parcelable) {
	if !p.Structured {
		if p.Custom != nil {
			r.renderCustomParcelable(p)
			return
		}
		r.renderOpaqueParcelable(p)
		return
	}

	needsRegistrar := r.fieldsNeedRegistrar(p.Fields)

	if len(p.Consts) != 0 {
		r.linef("const (")
		for _, c := range p.Consts {
			r.linef("\t%s %s = %s", c.GoName, r.typeExpr(c.Type), c.Value)
		}
		r.linef(")")
		r.linef("")
	}

	r.linef("type %s struct {", p.GoName)
	for _, field := range p.Fields {
		r.linef("\t%s %s", field.GoName, r.typeExpr(field.Type))
	}
	r.linef("}")
	r.linef("")

	if hasDefaultFields(p.Fields) {
		r.linef("func New%s() %s {", p.GoName, p.GoName)
		r.linef("\tv := %s{}", p.GoName)
		for _, field := range p.Fields {
			if field.DefaultValue == "" {
				continue
			}
			r.linef("\tv.%s = %s", field.GoName, field.DefaultValue)
		}
		r.linef("\treturn v")
		r.linef("}")
		r.linef("")
	}

	if needsRegistrar {
		r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", p.GoName, p.GoName)
		r.linef("\treturn write%sToParcelWithRegistrar(p, nil, v)", p.GoName)
		r.linef("}")
		r.linef("")
		r.linef("func write%sToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v %s) error {", p.GoName, p.GoName)
		r.linef("\tstartPos := p.Position()")
		r.linef("\tif err := p.WriteInt32(0); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		for _, field := range p.Fields {
			r.linef("\tif err := %s; err != nil {", r.contextWriteExpr("p", "v."+field.GoName, field.Type, "registrar"))
			r.linef("\t\treturn err")
			r.linef("\t}")
		}
		r.linef("\tendPos := p.Position()")
		r.linef("\tif err := p.SetPosition(startPos); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\tif err := p.WriteInt32(int32(endPos - startPos)); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\treturn p.SetPosition(endPos)")
		r.linef("}")
		r.linef("")
	} else {
		r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", p.GoName, p.GoName)
		r.linef("\tstartPos := p.Position()")
		r.linef("\tif err := p.WriteInt32(0); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		for _, field := range p.Fields {
			r.linef("\tif err := %s; err != nil {", r.contextWriteExpr("p", "v."+field.GoName, field.Type, ""))
			r.linef("\t\treturn err")
			r.linef("\t}")
		}
		r.linef("\tendPos := p.Position()")
		r.linef("\tif err := p.SetPosition(startPos); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\tif err := p.WriteInt32(int32(endPos - startPos)); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\treturn p.SetPosition(endPos)")
		r.linef("}")
		r.linef("")
	}

	r.linef("func read%sFromParcel(p *binder.Parcel) (ret %s, err error) {", p.GoName, p.GoName)
	if hasDefaultFields(p.Fields) {
		r.linef("\tret = New%s()", p.GoName)
	}
	r.linef("\tstartPos := p.Position()")
	r.linef("\tparcelableSize, err := p.ReadInt32()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn ret, err")
	r.linef("\t}")
	r.linef("\tif parcelableSize < 0 {")
	r.linef("\t\treturn ret, nil")
	r.linef("\t}")
	r.linef("\tendPos := startPos + int(parcelableSize)")
	r.linef("\tif endPos < startPos || endPos > p.Len() {")
	r.linef("\t\treturn ret, fmt.Errorf(\"%w: invalid parcelable size %d\", binder.ErrBadParcelable, parcelableSize)")
	r.linef("\t}")
	r.linef("\tdefer func() {")
	r.linef("\t\tif setErr := p.SetPosition(endPos); err == nil && setErr != nil {")
	r.linef("\t\t\terr = setErr")
	r.linef("\t\t}")
	r.linef("\t}()")
	for _, field := range p.Fields {
		r.linef("\t%sValue, err := %s", lowerFirst(field.GoName), r.contextReadExpr("p", field.Type))
		r.linef("\tif err != nil {")
		r.linef("\t\treturn ret, err")
		r.linef("\t}")
		r.linef("\tret.%s = %sValue", field.GoName, lowerFirst(field.GoName))
		r.linef("\tif p.Position()-startPos >= int(parcelableSize) {")
		r.linef("\t\treturn ret, nil")
		r.linef("\t}")
	}
	r.linef("\treturn ret, nil")
	r.linef("}")
	r.linef("")

	if needsRegistrar {
		r.linef("func writeNullable%sToParcel(p *binder.Parcel, v *%s) error {", p.GoName, p.GoName)
		r.linef("\treturn writeNullable%sToParcelWithRegistrar(p, nil, v)", p.GoName)
		r.linef("}")
		r.linef("")
		r.linef("func writeNullable%sToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v *%s) error {", p.GoName, p.GoName)
		r.linef("\tif v == nil {")
		r.linef("\t\treturn p.WriteInt32(0)")
		r.linef("\t}")
		r.linef("\tif err := p.WriteInt32(1); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\treturn write%sToParcelWithRegistrar(p, registrar, *v)", p.GoName)
		r.linef("}")
		r.linef("")
	} else {
		r.linef("func writeNullable%sToParcel(p *binder.Parcel, v *%s) error {", p.GoName, p.GoName)
		r.linef("\tif v == nil {")
		r.linef("\t\treturn p.WriteInt32(0)")
		r.linef("\t}")
		r.linef("\tif err := p.WriteInt32(1); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\treturn write%sToParcel(p, *v)", p.GoName)
		r.linef("}")
		r.linef("")
	}

	r.linef("func readNullable%sFromParcel(p *binder.Parcel) (*%s, error) {", p.GoName, p.GoName)
	r.linef("\tpresent, err := p.ReadInt32()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif present == 0 {")
	r.linef("\t\treturn nil, nil")
	r.linef("\t}")
	r.linef("\tv, err := read%sFromParcel(p)", p.GoName)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\treturn &v, nil")
	r.linef("}")
	r.linef("")
	r.renderParcelableExports(p, needsRegistrar)
}

func (r *goRenderer) renderOpaqueParcelable(p *gomodel.Parcelable) {
	r.linef("type %s struct {", p.GoName)
	r.linef("\tRawData []byte")
	r.linef("}")
	r.linef("")
	r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", p.GoName, p.GoName)
	r.linef("\tif len(v.RawData) > int(^uint32(0)>>1) {")
	r.linef("\t\treturn fmt.Errorf(\"%%w: opaque parcelable payload too large: %%d\", binder.ErrBadParcelable, len(v.RawData))")
	r.linef("\t}")
	r.linef("\tif err := p.WriteInt32(int32(len(v.RawData))); err != nil {")
	r.linef("\t\treturn err")
	r.linef("\t}")
	r.linef("\treturn p.WriteRawBytes(v.RawData)")
	r.linef("}")
	r.linef("")
	r.linef("func read%sFromParcel(p *binder.Parcel) (%s, error) {", p.GoName, p.GoName)
	r.linef("\tsize, err := p.ReadInt32()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn %s{}, err", p.GoName)
	r.linef("\t}")
	r.linef("\tif size < 0 {")
	r.linef("\t\treturn %s{}, fmt.Errorf(\"%%w: negative opaque parcelable size %%d\", binder.ErrBadParcelable, size)", p.GoName)
	r.linef("\t}")
	r.linef("\traw, err := p.ReadRawBytes(int(size))")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn %s{}, err", p.GoName)
	r.linef("\t}")
	r.linef("\treturn %s{RawData: raw}, nil", p.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func writeNullable%sToParcel(p *binder.Parcel, v *%s) error {", p.GoName, p.GoName)
	r.linef("\tif v == nil {")
	r.linef("\t\treturn p.WriteInt32(0)")
	r.linef("\t}")
	r.linef("\tif err := p.WriteInt32(1); err != nil {")
	r.linef("\t\treturn err")
	r.linef("\t}")
	r.linef("\treturn write%sToParcel(p, *v)", p.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func readNullable%sFromParcel(p *binder.Parcel) (*%s, error) {", p.GoName, p.GoName)
	r.linef("\tpresent, err := p.ReadInt32()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif present == 0 {")
	r.linef("\t\treturn nil, nil")
	r.linef("\t}")
	r.linef("\tv, err := read%sFromParcel(p)", p.GoName)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\treturn &v, nil")
	r.linef("}")
	r.linef("")
	r.renderParcelableExports(p, false)
}

func (r *goRenderer) renderCustomParcelable(p *gomodel.Parcelable) {
	custom := p.Custom
	goType := custom.ImportAlias + "." + custom.GoType

	r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", p.GoName, goType)
	r.linef("\treturn %s.%s(p, v)", custom.ImportAlias, custom.WriteFunc)
	r.linef("}")
	r.linef("")
	r.linef("func read%sFromParcel(p *binder.Parcel) (%s, error) {", p.GoName, goType)
	r.linef("\treturn %s.%s(p)", custom.ImportAlias, custom.ReadFunc)
	r.linef("}")
	r.linef("")
	r.linef("func writeNullable%sToParcel(p *binder.Parcel, v *%s) error {", p.GoName, goType)
	r.linef("\tif v == nil {")
	r.linef("\t\treturn p.WriteInt32(0)")
	r.linef("\t}")
	r.linef("\tif err := p.WriteInt32(1); err != nil {")
	r.linef("\t\treturn err")
	r.linef("\t}")
	r.linef("\treturn %s.%s(p, *v)", custom.ImportAlias, custom.WriteFunc)
	r.linef("}")
	r.linef("")
	r.linef("func readNullable%sFromParcel(p *binder.Parcel) (*%s, error) {", p.GoName, goType)
	r.linef("\tpresent, err := p.ReadInt32()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif present == 0 {")
	r.linef("\t\treturn nil, nil")
	r.linef("\t}")
	r.linef("\tv, err := %s.%s(p)", custom.ImportAlias, custom.ReadFunc)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\treturn &v, nil")
	r.linef("}")
	r.linef("")
	r.renderCustomParcelableExports(p, goType)
}

func (r *goRenderer) renderParcelableExports(p *gomodel.Parcelable, needsRegistrar bool) {
	r.linef("func Write%sToParcel(p *binder.Parcel, v %s) error {", p.GoName, p.GoName)
	r.linef("\treturn write%sToParcel(p, v)", p.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func Write%sToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v %s) error {", p.GoName, p.GoName)
	if needsRegistrar {
		r.linef("\treturn write%sToParcelWithRegistrar(p, registrar, v)", p.GoName)
	} else {
		r.linef("\treturn write%sToParcel(p, v)", p.GoName)
	}
	r.linef("}")
	r.linef("")
	r.linef("func Read%sFromParcel(p *binder.Parcel) (%s, error) {", p.GoName, p.GoName)
	r.linef("\treturn read%sFromParcel(p)", p.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func WriteNullable%sToParcel(p *binder.Parcel, v *%s) error {", p.GoName, p.GoName)
	r.linef("\treturn writeNullable%sToParcel(p, v)", p.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func WriteNullable%sToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v *%s) error {", p.GoName, p.GoName)
	if needsRegistrar {
		r.linef("\treturn writeNullable%sToParcelWithRegistrar(p, registrar, v)", p.GoName)
	} else {
		r.linef("\treturn writeNullable%sToParcel(p, v)", p.GoName)
	}
	r.linef("}")
	r.linef("")
	r.linef("func ReadNullable%sFromParcel(p *binder.Parcel) (*%s, error) {", p.GoName, p.GoName)
	r.linef("\treturn readNullable%sFromParcel(p)", p.GoName)
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderCustomParcelableExports(p *gomodel.Parcelable, goType string) {
	r.linef("func Write%sToParcel(p *binder.Parcel, v %s) error {", p.GoName, goType)
	r.linef("\treturn write%sToParcel(p, v)", p.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func Read%sFromParcel(p *binder.Parcel) (%s, error) {", p.GoName, goType)
	r.linef("\treturn read%sFromParcel(p)", p.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func WriteNullable%sToParcel(p *binder.Parcel, v *%s) error {", p.GoName, goType)
	r.linef("\treturn writeNullable%sToParcel(p, v)", p.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func ReadNullable%sFromParcel(p *binder.Parcel) (*%s, error) {", p.GoName, goType)
	r.linef("\treturn readNullable%sFromParcel(p)", p.GoName)
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderUnionExports(u *gomodel.Union, needsRegistrar bool) {
	r.linef("func Write%sToParcel(p *binder.Parcel, v %s) error {", u.GoName, u.GoName)
	r.linef("\treturn write%sToParcel(p, v)", u.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func Write%sToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v %s) error {", u.GoName, u.GoName)
	if needsRegistrar {
		r.linef("\treturn write%sToParcelWithRegistrar(p, registrar, v)", u.GoName)
	} else {
		r.linef("\treturn write%sToParcel(p, v)", u.GoName)
	}
	r.linef("}")
	r.linef("")
	r.linef("func Read%sFromParcel(p *binder.Parcel) (%s, error) {", u.GoName, u.GoName)
	r.linef("\treturn read%sFromParcel(p)", u.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func WriteNullable%sToParcel(p *binder.Parcel, v *%s) error {", u.GoName, u.GoName)
	r.linef("\treturn writeNullable%sToParcel(p, v)", u.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func WriteNullable%sToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v *%s) error {", u.GoName, u.GoName)
	if needsRegistrar {
		r.linef("\treturn writeNullable%sToParcelWithRegistrar(p, registrar, v)", u.GoName)
	} else {
		r.linef("\treturn writeNullable%sToParcel(p, v)", u.GoName)
	}
	r.linef("}")
	r.linef("")
	r.linef("func ReadNullable%sFromParcel(p *binder.Parcel) (*%s, error) {", u.GoName, u.GoName)
	r.linef("\treturn readNullable%sFromParcel(p)", u.GoName)
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderUnion(u *gomodel.Union) {
	needsRegistrar := r.fieldsNeedRegistrar(u.Fields)
	tagType := u.GoName + "Tag"

	r.linef("type %s int32", tagType)
	r.linef("")
	r.linef("const (")
	for i, field := range u.Fields {
		r.linef("\t%sTag%s %s = %d", u.GoName, field.GoName, tagType, i)
	}
	r.linef(")")
	r.linef("")

	r.linef("type %s struct {", u.GoName)
	r.linef("\tTag %s", tagType)
	for _, field := range u.Fields {
		r.linef("\t%s %s", field.GoName, r.typeExpr(field.Type))
	}
	r.linef("}")
	r.linef("")

	if needsRegistrar {
		r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", u.GoName, u.GoName)
		r.linef("\treturn write%sToParcelWithRegistrar(p, nil, v)", u.GoName)
		r.linef("}")
		r.linef("")
		r.linef("func write%sToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v %s) error {", u.GoName, u.GoName)
		r.linef("\tif err := p.WriteInt32(int32(v.Tag)); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\tswitch v.Tag {")
		for _, field := range u.Fields {
			r.linef("\tcase %sTag%s:", u.GoName, field.GoName)
			r.linef("\t\treturn %s", r.contextWriteExpr("p", "v."+field.GoName, field.Type, "registrar"))
		}
		r.linef("\tdefault:")
		r.linef("\t\treturn fmt.Errorf(\"%%w: invalid %s tag %%d\", binder.ErrBadParcelable, v.Tag)", u.GoName)
		r.linef("\t}")
		r.linef("}")
		r.linef("")
	} else {
		r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", u.GoName, u.GoName)
		r.linef("\tif err := p.WriteInt32(int32(v.Tag)); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\tswitch v.Tag {")
		for _, field := range u.Fields {
			r.linef("\tcase %sTag%s:", u.GoName, field.GoName)
			r.linef("\t\treturn %s", r.contextWriteExpr("p", "v."+field.GoName, field.Type, ""))
		}
		r.linef("\tdefault:")
		r.linef("\t\treturn fmt.Errorf(\"%%w: invalid %s tag %%d\", binder.ErrBadParcelable, v.Tag)", u.GoName)
		r.linef("\t}")
		r.linef("}")
		r.linef("")
	}

	r.linef("func read%sFromParcel(p *binder.Parcel) (%s, error) {", u.GoName, u.GoName)
	r.linef("\ttagValue, err := p.ReadInt32()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn %s{}, err", u.GoName)
	r.linef("\t}")
	r.linef("\tv := %s{Tag: %s(tagValue)}", u.GoName, tagType)
	r.linef("\tswitch v.Tag {")
	for _, field := range u.Fields {
		r.linef("\tcase %sTag%s:", u.GoName, field.GoName)
		r.linef("\t\tdecoded, err := %s", r.contextReadExpr("p", field.Type))
		r.linef("\t\tif err != nil {")
		r.linef("\t\t\treturn %s{}, err", u.GoName)
		r.linef("\t\t}")
		r.linef("\t\tv.%s = decoded", field.GoName)
		r.linef("\t\treturn v, nil")
	}
	r.linef("\tdefault:")
	r.linef("\t\treturn %s{}, fmt.Errorf(\"%%w: invalid %s tag %%d\", binder.ErrBadParcelable, v.Tag)", u.GoName, u.GoName)
	r.linef("\t}")
	r.linef("}")
	r.linef("")

	if needsRegistrar {
		r.linef("func writeNullable%sToParcel(p *binder.Parcel, v *%s) error {", u.GoName, u.GoName)
		r.linef("\treturn writeNullable%sToParcelWithRegistrar(p, nil, v)", u.GoName)
		r.linef("}")
		r.linef("")
		r.linef("func writeNullable%sToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v *%s) error {", u.GoName, u.GoName)
		r.linef("\tif v == nil {")
		r.linef("\t\treturn p.WriteInt32(0)")
		r.linef("\t}")
		r.linef("\tif err := p.WriteInt32(1); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\treturn write%sToParcelWithRegistrar(p, registrar, *v)", u.GoName)
		r.linef("}")
		r.linef("")
	} else {
		r.linef("func writeNullable%sToParcel(p *binder.Parcel, v *%s) error {", u.GoName, u.GoName)
		r.linef("\tif v == nil {")
		r.linef("\t\treturn p.WriteInt32(0)")
		r.linef("\t}")
		r.linef("\tif err := p.WriteInt32(1); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\treturn write%sToParcel(p, *v)", u.GoName)
		r.linef("}")
		r.linef("")
	}

	r.linef("func readNullable%sFromParcel(p *binder.Parcel) (*%s, error) {", u.GoName, u.GoName)
	r.linef("\tpresent, err := p.ReadInt32()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif present == 0 {")
	r.linef("\t\treturn nil, nil")
	r.linef("\t}")
	r.linef("\tv, err := read%sFromParcel(p)", u.GoName)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\treturn &v, nil")
	r.linef("}")
	r.linef("")
	r.renderUnionExports(u, needsRegistrar)
}

func (r *goRenderer) renderInterface(iface *gomodel.Interface) {
	r.linef("const %sDescriptor = %q", iface.GoName, iface.Descriptor)
	if iface.Stable {
		r.linef("const %sInterfaceVersion int32 = %d", iface.GoName, iface.Version)
		r.linef("const %sInterfaceHash = %q", iface.GoName, iface.Hash)
	}
	for _, c := range iface.Consts {
		r.linef("const %s %s = %s", c.GoName, r.typeExpr(c.Type), c.Value)
	}
	for _, method := range iface.Methods {
		r.linef("const %sTransaction%s uint32 = %d", iface.GoName, method.GoName, method.TransactionCode)
	}
	r.linef("")

	r.linef("type %s interface {", iface.GoName)
	for _, method := range iface.Methods {
		r.linef("\t%s(%s) (%s)", method.GoName, r.methodInputs(method), r.methodReturns(method))
	}
	r.linef("}")
	r.linef("")

	clientType := lowerFirst(iface.GoName) + "Client"
	r.linef("type %s struct {", clientType)
	r.linef("\ttarget binder.Binder")
	if iface.Stable {
		r.linef("\tversionMu sync.Mutex")
		r.linef("\tversionResolved bool")
		r.linef("\tcachedVersion int32")
		r.linef("\thashMu sync.Mutex")
		r.linef("\thashResolved bool")
		r.linef("\tcachedHash string")
	}
	r.linef("}")
	r.linef("")
	r.linef("func New%sClient(target binder.Binder) %s {", iface.GoName, iface.GoName)
	r.linef("\tif target == nil {")
	r.linef("\t\treturn nil")
	r.linef("\t}")
	if iface.Stable {
		r.linef("\treturn &%s{target: target, cachedVersion: -1, cachedHash: \"-1\"}", clientType)
	} else {
		r.linef("\treturn &%s{target: target}", clientType)
	}
	r.linef("}")
	r.linef("")
	r.linef("func (c *%s) AsBinder() binder.Binder {", clientType)
	r.linef("\tif c == nil {")
	r.linef("\t\treturn nil")
	r.linef("\t}")
	r.linef("\treturn c.target")
	r.linef("}")
	r.linef("")
	if iface.Stable {
		r.renderStableInterfaceHelpers(iface, clientType)
	}
	r.linef("func write%sToParcel(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v %s) error {", iface.GoName, iface.GoName)
	r.linef("\tif v == nil {")
	r.linef("\t\treturn p.WriteStrongBinder(nil)")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(binder.BinderProvider); ok {")
	r.linef("\t\treturn p.WriteStrongBinder(provider.AsBinder())")
	r.linef("\t}")
	r.linef("\tif registrar == nil {")
	r.linef("\t\treturn fmt.Errorf(\"%%w: no local handler registrar available for %s\", binder.ErrUnsupported)", iface.GoName)
	r.linef("\t}")
	r.linef("\tb, err := registrar.RegisterLocalHandler(New%sHandlerWithRegistrar(registrar, v))", iface.GoName)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn err")
	r.linef("\t}")
	r.linef("\treturn p.WriteStrongBinder(b)")
	r.linef("}")
	r.linef("")
	r.linef("func read%sFromParcel(p *binder.Parcel) (%s, error) {", iface.GoName, iface.GoName)
	r.linef("\tb, err := p.ReadStrongBinder()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif b == nil {")
	r.linef("\t\treturn nil, nil")
	r.linef("\t}")
	r.linef("\treturn New%sClient(b), nil", iface.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func Write%sToParcel(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v %s) error {", iface.GoName, iface.GoName)
	r.linef("\treturn write%sToParcel(p, registrar, v)", iface.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func Read%sFromParcel(p *binder.Parcel) (%s, error) {", iface.GoName, iface.GoName)
	r.linef("\treturn read%sFromParcel(p)", iface.GoName)
	r.linef("}")
	r.linef("")

	for _, method := range iface.Methods {
		r.renderProxyMethod(iface, clientType, method)
	}

	handlerType := lowerFirst(iface.GoName) + "Handler"
	r.linef("type %s struct {", handlerType)
	r.linef("\timpl %s", iface.GoName)
	r.linef("\tregistrar binder.LocalHandlerRegistrar")
	r.linef("}")
	r.linef("")
	r.linef("func New%sHandler(impl %s) binder.Handler {", iface.GoName, iface.GoName)
	r.linef("\treturn New%sHandlerWithRegistrar(nil, impl)", iface.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func New%sHandlerWithRegistrar(registrar binder.LocalHandlerRegistrar, impl %s) binder.Handler {", iface.GoName, iface.GoName)
	r.linef("\treturn &%s{impl: impl, registrar: registrar}", handlerType)
	r.linef("}")
	r.linef("")
	r.linef("func (h *%s) Descriptor() string {", handlerType)
	r.linef("\treturn %sDescriptor", iface.GoName)
	r.linef("}")
	r.linef("")
	if iface.Stable {
		r.linef("func (h *%s) InterfaceVersion() int32 {", handlerType)
		r.linef("\treturn %sInterfaceVersion", iface.GoName)
		r.linef("}")
		r.linef("")
		r.linef("func (h *%s) InterfaceHash() string {", handlerType)
		r.linef("\treturn %sInterfaceHash", iface.GoName)
		r.linef("}")
		r.linef("")
	}
	r.linef("func (h *%s) HandleTransact(ctx context.Context, code uint32, data *binder.Parcel) (*binder.Parcel, error) {", handlerType)
	r.linef("\tdescriptor, err := data.ReadInterfaceToken()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif descriptor != %sDescriptor {", iface.GoName)
	r.linef("\t\treturn nil, fmt.Errorf(\"%%w: descriptor %%q, want %%q\", binder.ErrBadParcelable, descriptor, %sDescriptor)", iface.GoName)
	r.linef("\t}")
	r.linef("\tswitch code {")
	for _, method := range iface.Methods {
		r.renderHandlerCase(iface, method)
	}
	r.linef("\tdefault:")
	r.linef("\t\treturn nil, fmt.Errorf(\"%%w: %s transaction code %%d\", binder.ErrUnknownTransaction, code)", iface.GoName)
	r.linef("\t}")
	r.linef("}")
	r.linef("")

	r.linef("func Check%sService(ctx context.Context, sm binder.ServiceManager, name string) (%s, error) {", iface.GoName, iface.GoName)
	r.linef("\tservice, err := sm.CheckService(ctx, name)")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\treturn New%sClient(service), nil", iface.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func Wait%sService(ctx context.Context, sm binder.ServiceManager, name string) (%s, error) {", iface.GoName, iface.GoName)
	r.linef("\tservice, err := sm.WaitService(ctx, name)")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\treturn New%sClient(service), nil", iface.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func Add%sService(ctx context.Context, sm binder.ServiceManager, name string, impl %s, opts ...binder.AddServiceOption) error {", iface.GoName, iface.GoName)
	r.linef("\tif registrar, ok := sm.(binder.LocalHandlerRegistrar); ok {")
	r.linef("\t\treturn sm.AddService(ctx, name, New%sHandlerWithRegistrar(registrar, impl), opts...)", iface.GoName)
	r.linef("\t}")
	r.linef("\treturn sm.AddService(ctx, name, New%sHandler(impl), opts...)", iface.GoName)
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderStableInterfaceHelpers(iface *gomodel.Interface, clientType string) {
	r.linef("func query%sInterfaceVersion(ctx context.Context, target binder.Binder) (int32, error) {", iface.GoName)
	r.linef("\tversion, err := binder.GetInterfaceVersion(ctx, target)")
	r.linef("\tif err != nil {")
	r.linef("\t\tif errors.Is(err, binder.ErrUnknownTransaction) {")
	r.linef("\t\t\treturn -1, nil")
	r.linef("\t\t}")
	r.linef("\t\treturn -1, err")
	r.linef("\t}")
	r.linef("\treturn version, nil")
	r.linef("}")
	r.linef("")
	r.linef("func query%sInterfaceHash(ctx context.Context, target binder.Binder) (string, error) {", iface.GoName)
	r.linef("\thash, err := binder.GetInterfaceHash(ctx, target)")
	r.linef("\tif err != nil {")
	r.linef("\t\tif errors.Is(err, binder.ErrUnknownTransaction) {")
	r.linef("\t\t\treturn \"-1\", nil")
	r.linef("\t\t}")
	r.linef("\t\treturn \"\", err")
	r.linef("\t}")
	r.linef("\treturn hash, nil")
	r.linef("}")
	r.linef("")
	r.linef("func (c *%s) InterfaceVersion(ctx context.Context) (int32, error) {", clientType)
	r.linef("\tif c == nil || c.target == nil {")
	r.linef("\t\treturn -1, binder.ErrUnsupported")
	r.linef("\t}")
	r.linef("\tc.versionMu.Lock()")
	r.linef("\tdefer c.versionMu.Unlock()")
	r.linef("\tif c.versionResolved {")
	r.linef("\t\treturn c.cachedVersion, nil")
	r.linef("\t}")
	r.linef("\tversion, err := query%sInterfaceVersion(ctx, c.target)", iface.GoName)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn -1, err")
	r.linef("\t}")
	r.linef("\tc.cachedVersion = version")
	r.linef("\tc.versionResolved = true")
	r.linef("\treturn version, nil")
	r.linef("}")
	r.linef("")
	r.linef("func (c *%s) InterfaceHash(ctx context.Context) (string, error) {", clientType)
	r.linef("\tif c == nil || c.target == nil {")
	r.linef("\t\treturn \"\", binder.ErrUnsupported")
	r.linef("\t}")
	r.linef("\tc.hashMu.Lock()")
	r.linef("\tdefer c.hashMu.Unlock()")
	r.linef("\tif c.hashResolved {")
	r.linef("\t\treturn c.cachedHash, nil")
	r.linef("\t}")
	r.linef("\thash, err := query%sInterfaceHash(ctx, c.target)", iface.GoName)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn \"\", err")
	r.linef("\t}")
	r.linef("\tc.cachedHash = hash")
	r.linef("\tc.hashResolved = true")
	r.linef("\treturn hash, nil")
	r.linef("}")
	r.linef("")
	r.linef("func Get%sInterfaceVersion(ctx context.Context, v %s) (int32, error) {", iface.GoName, iface.GoName)
	r.linef("\tif v == nil {")
	r.linef("\t\treturn -1, binder.ErrUnsupported")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(interface {")
	r.linef("\t\tInterfaceVersion(context.Context) (int32, error)")
	r.linef("\t}); ok {")
	r.linef("\t\treturn provider.InterfaceVersion(ctx)")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(binder.InterfaceVersionProvider); ok {")
	r.linef("\t\treturn provider.InterfaceVersion(), nil")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(binder.BinderProvider); ok {")
	r.linef("\t\treturn query%sInterfaceVersion(ctx, provider.AsBinder())", iface.GoName)
	r.linef("\t}")
	r.linef("\treturn -1, binder.ErrUnsupported")
	r.linef("}")
	r.linef("")
	r.linef("func Get%sInterfaceHash(ctx context.Context, v %s) (string, error) {", iface.GoName, iface.GoName)
	r.linef("\tif v == nil {")
	r.linef("\t\treturn \"\", binder.ErrUnsupported")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(interface {")
	r.linef("\t\tInterfaceHash(context.Context) (string, error)")
	r.linef("\t}); ok {")
	r.linef("\t\treturn provider.InterfaceHash(ctx)")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(binder.InterfaceHashProvider); ok {")
	r.linef("\t\treturn provider.InterfaceHash(), nil")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(binder.BinderProvider); ok {")
	r.linef("\t\treturn query%sInterfaceHash(ctx, provider.AsBinder())", iface.GoName)
	r.linef("\t}")
	r.linef("\treturn \"\", binder.ErrUnsupported")
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderProxyMethod(iface *gomodel.Interface, clientType string, method *gomodel.Method) {
	r.linef("func (c *%s) %s(%s) (%s) {", clientType, method.GoName, r.methodInputs(method), r.methodReturns(method))
	r.linef("\tif ctx == nil {")
	r.linef("\t\tctx = context.Background()")
	r.linef("\t}")
	r.linef("\treq := binder.NewParcel()")
	r.linef("\tif err := req.WriteInterfaceToken(%sDescriptor); err != nil {", iface.GoName)
	r.linef("\t\treturn %s", r.methodErrorReturn(method, "err"))
	r.linef("\t}")
	if r.methodNeedsRegistrar(method.Inputs) {
		r.linef("\tvar registrar binder.LocalHandlerRegistrar")
		r.linef("\tif resolved, ok := c.target.(binder.LocalHandlerRegistrar); ok {")
		r.linef("\t\tregistrar = resolved")
		r.linef("\t}")
	}
	for _, arg := range method.Inputs {
		r.linef("\tif err := %s; err != nil {", r.methodArgWriteExpr("req", arg.GoName, &arg, "registrar"))
		r.linef("\t\treturn %s", r.methodErrorReturn(method, "err"))
		r.linef("\t}")
	}
	flagExpr := "binder.FlagNone"
	if method.Oneway {
		flagExpr = "binder.FlagOneway"
	}
	if method.Oneway {
		r.linef("\t_, err := c.target.Transact(ctx, %sTransaction%s, req, %s)", iface.GoName, method.GoName, flagExpr)
		r.linef("\tif err != nil {")
		r.linef("\t\treturn %s", r.methodErrorReturn(method, "err"))
		r.linef("\t}")
		r.linef("\treturn nil")
		r.linef("}")
		r.linef("")
		return
	}
	r.linef("\tresp, err := c.target.Transact(ctx, %sTransaction%s, req, %s)", iface.GoName, method.GoName, flagExpr)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn %s", r.methodErrorReturn(method, "err"))
	r.linef("\t}")
	r.linef("\tif resp == nil {")
	r.linef("\t\treturn %s", r.methodErrorReturn(method, "binder.ErrBadParcelable"))
	r.linef("\t}")
	r.linef("\tif err := binder.ReadException(resp); err != nil {")
	r.linef("\t\treturn %s", r.methodErrorReturn(method, "err"))
	r.linef("\t}")
	retVar := "ret"
	if method.Return != nil {
		r.linef("\t%s, err := %s", retVar, r.methodValueReadExpr("resp", method.Return.Type, r.methodUsesTypedObjectEncoding(method.Return.Type)))
		r.linef("\tif err != nil {")
		r.linef("\t\treturn %s", r.methodErrorReturn(method, "err"))
		r.linef("\t}")
	}
	outVars := make([]string, 0, len(method.Outputs))
	for _, out := range method.Outputs {
		outVar := resultLocalName(out.GoName)
		outVars = append(outVars, outVar)
		r.linef("\t%s, err := %s", outVar, r.methodValueReadExpr("resp", out.Type, true))
		r.linef("\tif err != nil {")
		r.linef("\t\treturn %s", r.methodErrorReturn(method, "err"))
		r.linef("\t}")
	}
	r.linef("\treturn %s", r.methodSuccessReturnVars(method, retVar, outVars))
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderHandlerCase(iface *gomodel.Interface, method *gomodel.Method) {
	r.linef("\tcase %sTransaction%s:", iface.GoName, method.GoName)
	argVars := make([]string, 0, len(method.Inputs))
	for _, arg := range method.Inputs {
		argVar := argLocalName(arg.GoName)
		argVars = append(argVars, argVar)
		r.linef("\t\t%s, err := %s", argVar, r.methodArgReadExpr("data", &arg))
		r.linef("\t\tif err != nil {")
		r.linef("\t\t\treturn nil, err")
		r.linef("\t\t}")
	}
	callArgs := make([]string, 0, 1+len(method.Inputs))
	callArgs = append(callArgs, "ctx")
	callArgs = append(callArgs, argVars...)
	if method.Oneway {
		r.linef("\t\treturn nil, h.impl.%s(%s)", method.GoName, strings.Join(callArgs, ", "))
		return
	}

	resultVars := make([]string, 0, len(method.Outputs)+2)
	retVar := "ret"
	if method.Return != nil {
		resultVars = append(resultVars, retVar)
	}
	outVars := make([]string, 0, len(method.Outputs))
	for _, out := range method.Outputs {
		outVar := resultLocalName(out.GoName)
		outVars = append(outVars, outVar)
		resultVars = append(resultVars, outVar)
	}
	resultVars = append(resultVars, "err")
	assignOp := ":="
	if len(resultVars) == 1 && resultVars[0] == "err" {
		assignOp = "="
	}
	r.linef("\t\t%s %s h.impl.%s(%s)", strings.Join(resultVars, ", "), assignOp, method.GoName, strings.Join(callArgs, ", "))
	r.linef("\t\tif err != nil {")
	r.linef("\t\t\treply := binder.NewParcel()")
	r.linef("\t\t\thandled, writeErr := binder.TryWriteException(reply, err)")
	r.linef("\t\t\tif writeErr != nil {")
	r.linef("\t\t\t\treturn nil, writeErr")
	r.linef("\t\t\t}")
	r.linef("\t\t\tif handled {")
	r.linef("\t\t\t\treturn reply, nil")
	r.linef("\t\t\t}")
	r.linef("\t\t\treturn nil, err")
	r.linef("\t\t}")
	r.linef("\t\treply := binder.NewParcel()")
	r.linef("\t\tif err := binder.WriteNoException(reply); err != nil {")
	r.linef("\t\t\treturn nil, err")
	r.linef("\t\t}")
	if method.Return != nil {
		r.linef("\t\tif err := %s; err != nil {", r.methodValueWriteExpr("reply", retVar, method.Return.Type, "h.registrar", r.methodUsesTypedObjectEncoding(method.Return.Type)))
		r.linef("\t\t\treturn nil, err")
		r.linef("\t\t}")
	}
	for i, out := range method.Outputs {
		r.linef("\t\tif err := %s; err != nil {", r.methodValueWriteExpr("reply", outVars[i], out.Type, "h.registrar", true))
		r.linef("\t\t\treturn nil, err")
		r.linef("\t\t}")
	}
	r.linef("\t\treturn reply, nil")
}

func (r *goRenderer) methodInputs(method *gomodel.Method) string {
	parts := []string{"ctx context.Context"}
	for _, arg := range method.Inputs {
		parts = append(parts, fmt.Sprintf("%s %s", arg.GoName, r.methodInputTypeExpr(&arg)))
	}
	return strings.Join(parts, ", ")
}

func (r *goRenderer) methodReturns(method *gomodel.Method) string {
	if method.Oneway {
		return "error"
	}
	var parts []string
	if method.Return != nil {
		parts = append(parts, r.methodValueTypeExpr(method.Return.Type))
	}
	for _, out := range method.Outputs {
		parts = append(parts, r.methodValueTypeExpr(out.Type))
	}
	parts = append(parts, "error")
	return strings.Join(parts, ", ")
}

func (r *goRenderer) methodErrorReturn(method *gomodel.Method, errExpr string) string {
	if method.Oneway {
		return errExpr
	}
	var parts []string
	if method.Return != nil {
		parts = append(parts, r.methodValueZeroExpr(method.Return.Type))
	}
	for _, out := range method.Outputs {
		parts = append(parts, r.methodValueZeroExpr(out.Type))
	}
	parts = append(parts, errExpr)
	return strings.Join(parts, ", ")
}

func (r *goRenderer) methodSuccessReturn(method *gomodel.Method) string {
	if method.Oneway {
		return "nil"
	}
	return r.methodSuccessReturnVars(method, "ret", nil)
}

func (r *goRenderer) methodSuccessReturnVars(method *gomodel.Method, retVar string, outVars []string) string {
	if method.Oneway {
		return "nil"
	}
	var parts []string
	if method.Return != nil {
		parts = append(parts, retVar)
	}
	for i, out := range method.Outputs {
		if i < len(outVars) && outVars[i] != "" {
			parts = append(parts, outVars[i])
			continue
		}
		parts = append(parts, resultLocalName(out.GoName))
	}
	parts = append(parts, "nil")
	return strings.Join(parts, ", ")
}

func (r *goRenderer) methodArgWriteExpr(parcel string, value string, arg *gomodel.Field, registrar string) string {
	if arg == nil {
		return fmt.Sprintf("fmt.Errorf(\"%%w: nil method arg\", binder.ErrUnsupported)")
	}
	if r.methodInputUsesPointer(arg.Type) && !arg.Type.Nullable {
		return fmt.Sprintf(`func() error {
	if %s == nil {
		return fmt.Errorf("%%w: nil non-nullable argument %s", binder.ErrBadParcelable)
	}
	return %s
}()`, value, arg.GoName, r.contextWriteExpr(parcel, "*"+value, arg.Type, registrar))
	}
	return r.contextWriteExpr(parcel, value, arg.Type, registrar)
}

func (r *goRenderer) methodArgReadExpr(parcel string, arg *gomodel.Field) string {
	if arg == nil {
		return fmt.Sprintf("func() (any, error) { return nil, fmt.Errorf(\"%%w: nil method arg\", binder.ErrUnsupported) }()")
	}
	if r.methodInputUsesPointer(arg.Type) && !arg.Type.Nullable {
		return fmt.Sprintf(`func() (%s, error) {
	present, err := %s.ReadInt32()
	if err != nil {
		return nil, err
	}
	if present == 0 {
		return nil, binder.ErrBadParcelable
	}
	v, err := %s
	if err != nil {
		return nil, err
	}
	return &v, nil
}()`, r.methodInputTypeExpr(arg), parcel, r.readExpr(parcel, arg.Type))
	}
	return r.contextReadExpr(parcel, arg.Type)
}

func (r *goRenderer) methodInputTypeExpr(arg *gomodel.Field) string {
	if arg == nil || arg.Type == nil {
		return ""
	}
	if r.methodInputUsesPointer(arg.Type) && !arg.Type.Nullable {
		return "*" + r.typeExpr(arg.Type)
	}
	return r.typeExpr(arg.Type)
}

func (r *goRenderer) methodInputUsesPointer(typ *gomodel.Type) bool {
	if typ == nil {
		return false
	}
	switch typ.Kind {
	case gomodel.TypeParcelable, gomodel.TypeUnion:
		return true
	default:
		return false
	}
}

func (r *goRenderer) methodValueTypeExpr(typ *gomodel.Type) string {
	if typ == nil {
		return ""
	}
	if r.methodValueUsesPointer(typ) {
		base := r.nonNullableType(typ)
		return "*" + r.typeExpr(base)
	}
	return r.typeExpr(typ)
}

func (r *goRenderer) methodValueZeroExpr(typ *gomodel.Type) string {
	if typ == nil {
		return "nil"
	}
	if r.methodValueUsesPointer(typ) {
		return "nil"
	}
	return r.zeroExpr(typ)
}

func (r *goRenderer) methodValueUsesPointer(typ *gomodel.Type) bool {
	if typ == nil {
		return false
	}
	switch typ.Kind {
	case gomodel.TypeParcelable, gomodel.TypeUnion:
		return true
	default:
		return false
	}
}

func (r *goRenderer) methodValueWriteExpr(parcel string, value string, typ *gomodel.Type, registrar string, typedObject bool) string {
	if typ == nil {
		return fmt.Sprintf("fmt.Errorf(\"%%w: nil method value type\", binder.ErrUnsupported)")
	}
	if r.methodValueUsesPointer(typ) && !typ.Nullable {
		return fmt.Sprintf(`func() error {
	if %s == nil {
		return fmt.Errorf("%%w: nil non-nullable return value", binder.ErrBadParcelable)
	}
	return %s
}()`, value, r.contextWriteExpr(parcel, "*"+value, typ, registrar))
	}
	return r.contextWriteExpr(parcel, value, typ, registrar)
}

func (r *goRenderer) methodValueReadExpr(parcel string, typ *gomodel.Type, typedObject bool) string {
	if typ == nil {
		return fmt.Sprintf("func() (any, error) { return nil, fmt.Errorf(\"%%w: nil method value type\", binder.ErrUnsupported) }()")
	}
	if r.methodValueUsesPointer(typ) {
		base := r.nonNullableType(typ)
		if typ.Nullable {
			return r.contextReadExpr(parcel, typ)
		}
		return fmt.Sprintf(`func() (%s, error) {
	present, err := %s.ReadInt32()
	if err != nil {
		return nil, err
	}
	if present == 0 {
		return nil, binder.ErrBadParcelable
	}
	v, err := %s
	if err != nil {
		return nil, err
	}
	return &v, nil
}()`, r.methodValueTypeExpr(typ), parcel, r.readExpr(parcel, base))
	}
	return r.contextReadExpr(parcel, typ)
}

func (r *goRenderer) methodUsesTypedObjectEncoding(typ *gomodel.Type) bool {
	if typ == nil {
		return false
	}
	switch typ.Kind {
	case gomodel.TypeParcelable, gomodel.TypeUnion, gomodel.TypeParcelFileDescriptor:
		return true
	default:
		return false
	}
}

func (r *goRenderer) contextWriteExpr(parcel string, value string, typ *gomodel.Type, registrar string) string {
	if !r.methodUsesTypedObjectEncoding(typ) {
		return r.writeExpr(parcel, value, typ, registrar)
	}
	if typ.Nullable {
		return r.writeExpr(parcel, value, typ, registrar)
	}
	nonNullable := *typ
	nonNullable.Nullable = false
	return fmt.Sprintf(`func() error {
	if err := %s.WriteInt32(1); err != nil {
		return err
	}
	return %s
}()`, parcel, r.writeExpr(parcel, value, &nonNullable, registrar))
}

func (r *goRenderer) contextReadExpr(parcel string, typ *gomodel.Type) string {
	if !r.methodUsesTypedObjectEncoding(typ) {
		return r.readExpr(parcel, typ)
	}
	if typ.Nullable {
		return r.readExpr(parcel, typ)
	}
	nonNullable := *typ
	nonNullable.Nullable = false
	return fmt.Sprintf(`func() (%s, error) {
	present, err := %s.ReadInt32()
	if err != nil {
		return %s, err
	}
	if present == 0 {
		return %s, nil
	}
	return %s
}()`, r.typeExpr(typ), parcel, r.zeroExpr(typ), r.zeroExpr(typ), r.readExpr(parcel, &nonNullable))
}

func (r *goRenderer) writeExpr(parcel string, value string, typ *gomodel.Type, registrar string) string {
	switch typ.Kind {
	case gomodel.TypeBool:
		return fmt.Sprintf("%s.WriteBool(%s)", parcel, value)
	case gomodel.TypeByte:
		return fmt.Sprintf("%s.WriteByte(%s)", parcel, value)
	case gomodel.TypeChar:
		return fmt.Sprintf("%s.WriteChar(%s)", parcel, value)
	case gomodel.TypeInt32:
		return fmt.Sprintf("%s.WriteInt32(%s)", parcel, value)
	case gomodel.TypeInt64:
		return fmt.Sprintf("%s.WriteInt64(%s)", parcel, value)
	case gomodel.TypeFloat32:
		return fmt.Sprintf("%s.WriteFloat32(%s)", parcel, value)
	case gomodel.TypeFloat64:
		return fmt.Sprintf("%s.WriteFloat64(%s)", parcel, value)
	case gomodel.TypeString:
		if typ.Nullable {
			return fmt.Sprintf("%s.WriteNullableString(%s)", parcel, value)
		}
		return fmt.Sprintf("%s.WriteString(%s)", parcel, value)
	case gomodel.TypeParcelable:
		if cfg, alias, ok := r.customParcelableConfig(typ); ok {
			return r.customParcelableWriteExpr(parcel, value, typ, cfg, alias)
		}
		if qualifier := r.generatedQualifier(typ); qualifier != "" {
			if registrar != "" {
				if typ.Nullable {
					return fmt.Sprintf("%sWriteNullable%sToParcelWithRegistrar(%s, %s, %s)", qualifier, typ.NamedGo, parcel, registrarExpr(registrar), value)
				}
				return fmt.Sprintf("%sWrite%sToParcelWithRegistrar(%s, %s, %s)", qualifier, typ.NamedGo, parcel, registrarExpr(registrar), value)
			}
			if typ.Nullable {
				return fmt.Sprintf("%sWriteNullable%sToParcel(%s, %s)", qualifier, typ.NamedGo, parcel, value)
			}
			return fmt.Sprintf("%sWrite%sToParcel(%s, %s)", qualifier, typ.NamedGo, parcel, value)
		}
		if r.typeNeedsRegistrar(typ) {
			if typ.Nullable {
				return fmt.Sprintf("writeNullable%sToParcelWithRegistrar(%s, %s, %s)", typ.NamedGo, parcel, registrarExpr(registrar), value)
			}
			return fmt.Sprintf("write%sToParcelWithRegistrar(%s, %s, %s)", typ.NamedGo, parcel, registrarExpr(registrar), value)
		}
		if typ.Nullable {
			return fmt.Sprintf("writeNullable%sToParcel(%s, %s)", typ.NamedGo, parcel, value)
		}
		return fmt.Sprintf("write%sToParcel(%s, %s)", typ.NamedGo, parcel, value)
	case gomodel.TypeEnum:
		if qualifier := r.generatedQualifier(typ); qualifier != "" {
			return fmt.Sprintf("%sWrite%sToParcel(%s, %s)", qualifier, typ.NamedGo, parcel, value)
		}
		return fmt.Sprintf("write%sToParcel(%s, %s)", typ.NamedGo, parcel, value)
	case gomodel.TypeUnion:
		if qualifier := r.generatedQualifier(typ); qualifier != "" {
			if registrar != "" {
				if typ.Nullable {
					return fmt.Sprintf("%sWriteNullable%sToParcelWithRegistrar(%s, %s, %s)", qualifier, typ.NamedGo, parcel, registrarExpr(registrar), value)
				}
				return fmt.Sprintf("%sWrite%sToParcelWithRegistrar(%s, %s, %s)", qualifier, typ.NamedGo, parcel, registrarExpr(registrar), value)
			}
			if typ.Nullable {
				return fmt.Sprintf("%sWriteNullable%sToParcel(%s, %s)", qualifier, typ.NamedGo, parcel, value)
			}
			return fmt.Sprintf("%sWrite%sToParcel(%s, %s)", qualifier, typ.NamedGo, parcel, value)
		}
		if r.typeNeedsRegistrar(typ) {
			if typ.Nullable {
				return fmt.Sprintf("writeNullable%sToParcelWithRegistrar(%s, %s, %s)", typ.NamedGo, parcel, registrarExpr(registrar), value)
			}
			return fmt.Sprintf("write%sToParcelWithRegistrar(%s, %s, %s)", typ.NamedGo, parcel, registrarExpr(registrar), value)
		}
		if typ.Nullable {
			return fmt.Sprintf("writeNullable%sToParcel(%s, %s)", typ.NamedGo, parcel, value)
		}
		return fmt.Sprintf("write%sToParcel(%s, %s)", typ.NamedGo, parcel, value)
	case gomodel.TypeBinder:
		return fmt.Sprintf("%s.WriteStrongBinder(%s)", parcel, value)
	case gomodel.TypeFileDescriptor:
		return fmt.Sprintf("%s.WriteFileDescriptor(%s)", parcel, value)
	case gomodel.TypeParcelFileDescriptor:
		if typ.Nullable {
			return fmt.Sprintf("%s(%s, %s)", r.nullableParcelFileDescriptorWriterName(), parcel, value)
		}
		return fmt.Sprintf("%s.WriteParcelFileDescriptor(%s)", parcel, value)
	case gomodel.TypeInterface:
		if qualifier := r.generatedQualifier(typ); qualifier != "" {
			return fmt.Sprintf("%sWrite%sToParcel(%s, %s, %s)", qualifier, typ.NamedGo, parcel, registrarExpr(registrar), value)
		}
		return fmt.Sprintf("write%sToParcel(%s, %s, %s)", typ.NamedGo, parcel, registrarExpr(registrar), value)
	case gomodel.TypeMap:
		if r.isRawMapType(typ) {
			return fmt.Sprintf("binder.WriteMap(%s, %s, func(p *binder.Parcel, item any) error { return binder.WriteDynamicValue(p, item) }, func(p *binder.Parcel, item any) error { return binder.WriteDynamicValue(p, item) })", parcel, value)
		}
		return fmt.Sprintf("binder.WriteMap(%s, %s, func(p *binder.Parcel, item %s) error { return %s }, func(p *binder.Parcel, item %s) error { return %s })", parcel, value, r.typeExpr(typ.Key), r.contextWriteExpr("p", "item", typ.Key, registrar), r.typeExpr(typ.Value), r.contextWriteExpr("p", "item", typ.Value, registrar))
	case gomodel.TypeSlice:
		return fmt.Sprintf("binder.WriteSlice(%s, %s, func(p *binder.Parcel, item %s) error { return %s })", parcel, value, r.typeExpr(typ.Elem), r.contextWriteExpr("p", "item", typ.Elem, registrar))
	case gomodel.TypeArray:
		return fmt.Sprintf("binder.WriteFixedSlice(%s, %s, %d, func(p *binder.Parcel, item %s) error { return %s })", parcel, value, typ.FixedLen, r.typeExpr(typ.Elem), r.contextWriteExpr("p", "item", typ.Elem, registrar))
	default:
		return fmt.Sprintf("fmt.Errorf(\"%%w: unsupported type %s\", binder.ErrUnsupported)", r.typeExpr(typ))
	}
}

func (r *goRenderer) readExpr(parcel string, typ *gomodel.Type) string {
	switch typ.Kind {
	case gomodel.TypeBool:
		return fmt.Sprintf("%s.ReadBool()", parcel)
	case gomodel.TypeByte:
		return fmt.Sprintf("%s.ReadByte()", parcel)
	case gomodel.TypeChar:
		return fmt.Sprintf("%s.ReadChar()", parcel)
	case gomodel.TypeInt32:
		return fmt.Sprintf("%s.ReadInt32()", parcel)
	case gomodel.TypeInt64:
		return fmt.Sprintf("%s.ReadInt64()", parcel)
	case gomodel.TypeFloat32:
		return fmt.Sprintf("%s.ReadFloat32()", parcel)
	case gomodel.TypeFloat64:
		return fmt.Sprintf("%s.ReadFloat64()", parcel)
	case gomodel.TypeString:
		if typ.Nullable {
			return fmt.Sprintf("%s.ReadNullableString()", parcel)
		}
		return fmt.Sprintf("%s.ReadString()", parcel)
	case gomodel.TypeParcelable:
		if cfg, alias, ok := r.customParcelableConfig(typ); ok {
			return r.customParcelableReadExpr(parcel, typ, cfg, alias)
		}
		if qualifier := r.generatedQualifier(typ); qualifier != "" {
			if typ.Nullable {
				return fmt.Sprintf("%sReadNullable%sFromParcel(%s)", qualifier, typ.NamedGo, parcel)
			}
			return fmt.Sprintf("%sRead%sFromParcel(%s)", qualifier, typ.NamedGo, parcel)
		}
		if typ.Nullable {
			return fmt.Sprintf("readNullable%sFromParcel(%s)", typ.NamedGo, parcel)
		}
		return fmt.Sprintf("read%sFromParcel(%s)", typ.NamedGo, parcel)
	case gomodel.TypeEnum:
		if qualifier := r.generatedQualifier(typ); qualifier != "" {
			return fmt.Sprintf("%sRead%sFromParcel(%s)", qualifier, typ.NamedGo, parcel)
		}
		return fmt.Sprintf("read%sFromParcel(%s)", typ.NamedGo, parcel)
	case gomodel.TypeUnion:
		if qualifier := r.generatedQualifier(typ); qualifier != "" {
			if typ.Nullable {
				return fmt.Sprintf("%sReadNullable%sFromParcel(%s)", qualifier, typ.NamedGo, parcel)
			}
			return fmt.Sprintf("%sRead%sFromParcel(%s)", qualifier, typ.NamedGo, parcel)
		}
		if typ.Nullable {
			return fmt.Sprintf("readNullable%sFromParcel(%s)", typ.NamedGo, parcel)
		}
		return fmt.Sprintf("read%sFromParcel(%s)", typ.NamedGo, parcel)
	case gomodel.TypeBinder:
		return fmt.Sprintf("%s.ReadStrongBinder()", parcel)
	case gomodel.TypeFileDescriptor:
		return fmt.Sprintf("%s.ReadFileDescriptor()", parcel)
	case gomodel.TypeParcelFileDescriptor:
		if typ.Nullable {
			return fmt.Sprintf("%s(%s)", r.nullableParcelFileDescriptorReaderName(), parcel)
		}
		return fmt.Sprintf("%s(%s)", r.requiredParcelFileDescriptorReaderName(), parcel)
	case gomodel.TypeInterface:
		if qualifier := r.generatedQualifier(typ); qualifier != "" {
			return fmt.Sprintf("%sRead%sFromParcel(%s)", qualifier, typ.NamedGo, parcel)
		}
		return fmt.Sprintf("read%sFromParcel(%s)", typ.NamedGo, parcel)
	case gomodel.TypeMap:
		if r.isRawMapType(typ) {
			return fmt.Sprintf("binder.ReadMap(%s, func(p *binder.Parcel) (any, error) { return binder.ReadDynamicValue(p) }, func(p *binder.Parcel) (any, error) { return binder.ReadDynamicValue(p) })", parcel)
		}
		return fmt.Sprintf("binder.ReadMap(%s, func(p *binder.Parcel) (%s, error) { return %s }, func(p *binder.Parcel) (%s, error) { return %s })", parcel, r.typeExpr(typ.Key), r.contextReadExpr("p", typ.Key), r.typeExpr(typ.Value), r.contextReadExpr("p", typ.Value))
	case gomodel.TypeSlice:
		return fmt.Sprintf("binder.ReadSlice(%s, func(p *binder.Parcel) (%s, error) { return %s })", parcel, r.typeExpr(typ.Elem), r.contextReadExpr("p", typ.Elem))
	case gomodel.TypeArray:
		return fmt.Sprintf("binder.ReadFixedSlice(%s, %d, func(p *binder.Parcel) (%s, error) { return %s })", parcel, typ.FixedLen, r.typeExpr(typ.Elem), r.contextReadExpr("p", typ.Elem))
	default:
		return fmt.Sprintf("func() (%s, error) { return %s, fmt.Errorf(\"%%w: unsupported type %s\", binder.ErrUnsupported) }()", r.typeExpr(typ), r.zeroExpr(typ), r.typeExpr(typ))
	}
}

func parseInt(value string) (int64, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return 0, fmt.Errorf("empty")
	}
	var sign int64 = 1
	if strings.HasPrefix(value, "-") {
		sign = -1
		value = strings.TrimPrefix(value, "-")
	}
	var n int64
	for _, r := range value {
		if r < '0' || r > '9' {
			return 0, fmt.Errorf("not decimal")
		}
		n = n*10 + int64(r-'0')
	}
	return sign * n, nil
}

func hasDefaultFields(fields []gomodel.Field) bool {
	for _, field := range fields {
		if field.DefaultValue != "" {
			return true
		}
	}
	return false
}

func lowerFirst(name string) string {
	if name == "" {
		return ""
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func argLocalName(name string) string {
	return uniqueLocalName(name, "Arg")
}

func resultLocalName(name string) string {
	return uniqueLocalName(name, "Value")
}

func uniqueLocalName(name string, suffix string) string {
	base := lowerFirst(name)
	if base == "" {
		base = "value"
	}
	base = sanitizeIdentifier(base)
	if base == "" {
		base = "value"
	}
	return base + suffix
}

func sanitizeIdentifier(name string) string {
	var b strings.Builder
	for i, r := range name {
		if ('a' <= r && r <= 'z') || ('A' <= r && r <= 'Z') || r == '_' || (i > 0 && '0' <= r && r <= '9') {
			b.WriteRune(r)
			continue
		}
		b.WriteByte('_')
	}
	return b.String()
}

func (r *goRenderer) nullableParcelFileDescriptorWriterName() string {
	return r.fileHelperPrefix() + "WriteNullableParcelFileDescriptorToParcel"
}

func (r *goRenderer) nullableParcelFileDescriptorReaderName() string {
	return r.fileHelperPrefix() + "ReadNullableParcelFileDescriptorFromParcel"
}

func (r *goRenderer) requiredParcelFileDescriptorReaderName() string {
	return r.fileHelperPrefix() + "ReadRequiredParcelFileDescriptorFromParcel"
}

func (r *goRenderer) fileHelperPrefix() string {
	base := "aidlGenerated"
	if r.model != nil && r.model.SourcePath != "" {
		base = strings.TrimSuffix(filepath.Base(r.model.SourcePath), filepath.Ext(r.model.SourcePath))
	}
	prefix := lowerFirst(sanitizeIdentifier(base))
	if prefix == "" {
		return "aidlGenerated"
	}
	if prefix[0] >= '0' && prefix[0] <= '9' {
		return "aidl" + prefix
	}
	return prefix
}

func (r *goRenderer) customParcelableConfig(typ *gomodel.Type) (gomodel.CustomParcelableConfig, string, bool) {
	if typ == nil || typ.Kind != gomodel.TypeParcelable {
		return gomodel.CustomParcelableConfig{}, "", false
	}
	cfg, ok := r.customParcelables[typ.AIDLName]
	if ok && cfg.GoPackage != "" && cfg.GoType != "" && cfg.WriteFunc != "" && cfg.ReadFunc != "" {
		return cfg, customImportAlias(cfg.GoPackage), true
	}
	if typ.NamedGo != "" {
		if p := r.parcelablesByName[typ.NamedGo]; p != nil && p.Custom != nil {
			return gomodel.CustomParcelableConfig{
				AIDLName:  typ.AIDLName,
				GoPackage: p.Custom.GoPackage,
				GoType:    p.Custom.GoType,
				WriteFunc: p.Custom.WriteFunc,
				ReadFunc:  p.Custom.ReadFunc,
				Nullable:  p.Custom.Nullable,
			}, p.Custom.ImportAlias, true
		}
	}
	return gomodel.CustomParcelableConfig{}, "", false
}

func (r *goRenderer) customParcelableWriteExpr(parcel string, value string, typ *gomodel.Type, cfg gomodel.CustomParcelableConfig, alias string) string {
	writeCall := fmt.Sprintf("%s.%s(%s, %s)", alias, cfg.WriteFunc, parcel, value)
	if !typ.Nullable {
		return writeCall
	}
	return fmt.Sprintf(`func() error {
	if %s == nil {
		return %s.WriteInt32(0)
	}
	if err := %s.WriteInt32(1); err != nil {
		return err
	}
	return %s.%s(%s, *%s)
}()`, value, parcel, parcel, alias, cfg.WriteFunc, parcel, value)
}

func (r *goRenderer) customParcelableReadExpr(parcel string, typ *gomodel.Type, cfg gomodel.CustomParcelableConfig, alias string) string {
	readCall := fmt.Sprintf("%s.%s(%s)", alias, cfg.ReadFunc, parcel)
	if !typ.Nullable {
		return readCall
	}
	return fmt.Sprintf(`func() (%s, error) {
	present, err := %s.ReadInt32()
	if err != nil {
		return nil, err
	}
	if present == 0 {
		return nil, nil
	}
	value, err := %s.%s(%s)
	if err != nil {
		return nil, err
	}
	return &value, nil
}()`, typ.GoExpr, parcel, alias, cfg.ReadFunc, parcel)
}

func registrarExpr(name string) string {
	if name == "" {
		return "nil"
	}
	return name
}

func (r *goRenderer) methodNeedsRegistrar(fields []gomodel.Field) bool {
	return r.fieldsNeedRegistrar(fields)
}

func (r *goRenderer) fieldsNeedRegistrar(fields []gomodel.Field) bool {
	for _, field := range fields {
		if r.typeNeedsRegistrar(field.Type) {
			return true
		}
	}
	return false
}

func (r *goRenderer) typeNeedsRegistrar(typ *gomodel.Type) bool {
	return r.typeNeedsRegistrarSeen(typ, map[string]struct{}{})
}

func (r *goRenderer) typeNeedsRegistrarSeen(typ *gomodel.Type, seen map[string]struct{}) bool {
	if typ == nil {
		return false
	}
	switch typ.Kind {
	case gomodel.TypeInterface:
		return true
	case gomodel.TypeSlice, gomodel.TypeArray:
		return r.typeNeedsRegistrarSeen(typ.Elem, seen)
	case gomodel.TypeMap:
		return r.typeNeedsRegistrarSeen(typ.Key, seen) || r.typeNeedsRegistrarSeen(typ.Value, seen)
	case gomodel.TypeParcelable:
		if _, _, ok := r.customParcelableConfig(typ); ok {
			return false
		}
		if typ.DeclPackage != "" && typ.DeclPackage != r.model.AIDLPackage {
			return true
		}
		if typ.NamedGo == "" {
			return false
		}
		key := "parcelable:" + typ.NamedGo
		if _, ok := seen[key]; ok {
			return false
		}
		seen[key] = struct{}{}
		defer delete(seen, key)
		p := r.parcelablesByName[typ.NamedGo]
		if p == nil {
			return false
		}
		return r.fieldsNeedRegistrarSeen(p.Fields, seen)
	case gomodel.TypeUnion:
		if typ.DeclPackage != "" && typ.DeclPackage != r.model.AIDLPackage {
			return true
		}
		if typ.NamedGo == "" {
			return false
		}
		key := "union:" + typ.NamedGo
		if _, ok := seen[key]; ok {
			return false
		}
		seen[key] = struct{}{}
		defer delete(seen, key)
		u := r.unionsByName[typ.NamedGo]
		if u == nil {
			return false
		}
		return r.fieldsNeedRegistrarSeen(u.Fields, seen)
	default:
		return false
	}
}

func (r *goRenderer) fieldsNeedRegistrarSeen(fields []gomodel.Field, seen map[string]struct{}) bool {
	for _, field := range fields {
		if r.typeNeedsRegistrarSeen(field.Type, seen) {
			return true
		}
	}
	return false
}

func (r *goRenderer) linef(format string, args ...any) {
	if len(args) == 0 {
		r.buf.WriteString(format)
		r.buf.WriteByte('\n')
		return
	}
	fmt.Fprintf(&r.buf, format+"\n", args...)
}
