package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"path/filepath"
	"sort"
	"strings"

	"github.com/wdsgyj/libbinder-go/internal/aidl/gomodel"
)

const defaultRuntimeImport = "github.com/wdsgyj/libbinder-go/binder"

type GoOptions struct {
	RuntimeImportPath string
	TypeMappingsPath  string
}

type OutputFile struct {
	Path    string
	Content []byte
}

func RenderGo(model *gomodel.File, opts GoOptions) ([]OutputFile, error) {
	if model == nil {
		return nil, fmt.Errorf("nil model")
	}
	if len(model.ExternalRefs) != 0 {
		return nil, fmt.Errorf("unresolved external references: %s", strings.Join(model.ExternalRefs, ", "))
	}

	renderer := &goRenderer{
		model:             model,
		runtimeImportPath: opts.RuntimeImportPath,
		typeMappingsPath:  opts.TypeMappingsPath,
	}
	if renderer.runtimeImportPath == "" {
		renderer.runtimeImportPath = defaultRuntimeImport
	}
	renderer.indexModel()
	if err := renderer.validate(); err != nil {
		return nil, err
	}

	content, err := renderer.render()
	if err != nil {
		return nil, err
	}

	return []OutputFile{{
		Path:    outputPath(model),
		Content: content,
	}}, nil
}

type goRenderer struct {
	model             *gomodel.File
	runtimeImportPath string
	typeMappingsPath  string
	buf               bytes.Buffer
	parcelablesByName map[string]*gomodel.Parcelable
	unionsByName      map[string]*gomodel.Union
}

type importSpec struct {
	Path  string
	Alias string
}

func (r *goRenderer) indexModel() {
	r.parcelablesByName = make(map[string]*gomodel.Parcelable, len(r.model.Parcelables))
	for _, p := range r.model.Parcelables {
		r.parcelablesByName[p.GoName] = p
	}
	r.unionsByName = make(map[string]*gomodel.Union, len(r.model.Unions))
	for _, u := range r.model.Unions {
		r.unionsByName[u.GoName] = u
	}
}

func (r *goRenderer) render() ([]byte, error) {
	r.linef("// Code generated by aidlgen. DO NOT EDIT.")
	r.linef("")
	r.linef("package %s", r.model.GoPackage)
	r.linef("")

	imports := r.imports()
	if len(imports) != 0 {
		r.linef("import (")
		for _, imp := range imports {
			if imp.Alias != "" {
				r.linef("\t%s %q", imp.Alias, imp.Path)
				continue
			}
			r.linef("\t%q", imp.Path)
		}
		r.linef(")")
		r.linef("")
	}

	r.renderParcelFileDescriptorHelpers()
	for _, enum := range r.model.Enums {
		r.renderEnum(enum)
	}
	for _, parcelable := range r.model.Parcelables {
		r.renderParcelable(parcelable)
	}
	for _, union := range r.model.Unions {
		r.renderUnion(union)
	}
	for _, iface := range r.model.Interfaces {
		r.renderInterface(iface)
	}

	out, err := format.Source(r.buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w\n%s", err, r.buf.String())
	}
	return out, nil
}

func (r *goRenderer) validate() error {
	for _, p := range r.model.Parcelables {
		if !p.Structured {
			if p.Custom == nil {
				if r.typeMappingsPath != "" {
					return fmt.Errorf("custom parcelable %s has no sidecar mapping in %s", p.AIDLName, r.typeMappingsPath)
				}
				return fmt.Errorf("custom parcelable %s has no sidecar mapping", p.AIDLName)
			}
			continue
		}
		for _, field := range p.Fields {
			if err := r.validateTypeUsage(field.Type, false); err != nil {
				return fmt.Errorf("parcelable %s field %s: %w", p.GoName, field.GoName, err)
			}
		}
	}
	for _, u := range r.model.Unions {
		for _, field := range u.Fields {
			if err := r.validateTypeUsage(field.Type, false); err != nil {
				return fmt.Errorf("union %s field %s: %w", u.GoName, field.GoName, err)
			}
		}
	}
	for _, iface := range r.model.Interfaces {
		if iface.Stable && (iface.Version <= 0 || iface.Hash == "") {
			if r.typeMappingsPath != "" {
				return fmt.Errorf("stable interface %s missing version/hash mapping in %s", iface.AIDLName, r.typeMappingsPath)
			}
			return fmt.Errorf("stable interface %s missing version/hash mapping", iface.AIDLName)
		}
		for _, c := range iface.Consts {
			if err := r.validateConstType(c.Type); err != nil {
				return fmt.Errorf("interface %s const %s: %w", iface.GoName, c.GoName, err)
			}
		}
		for _, method := range iface.Methods {
			if method.Return != nil {
				if err := r.validateTypeUsage(method.Return.Type, true); err != nil {
					return fmt.Errorf("method %s.%s return: %w", iface.GoName, method.GoName, err)
				}
			}
			for _, arg := range method.Inputs {
				if err := r.validateTypeUsage(arg.Type, true); err != nil {
					return fmt.Errorf("method %s.%s input %s: %w", iface.GoName, method.GoName, arg.GoName, err)
				}
			}
			for _, arg := range method.Outputs {
				if err := r.validateTypeUsage(arg.Type, true); err != nil {
					return fmt.Errorf("method %s.%s output %s: %w", iface.GoName, method.GoName, arg.GoName, err)
				}
			}
		}
	}
	return nil
}

func (r *goRenderer) validateConstType(typ *gomodel.Type) error {
	if typ == nil {
		return fmt.Errorf("nil type")
	}
	switch typ.Kind {
	case gomodel.TypeBool, gomodel.TypeByte, gomodel.TypeChar, gomodel.TypeInt32, gomodel.TypeInt64, gomodel.TypeFloat32, gomodel.TypeFloat64, gomodel.TypeString, gomodel.TypeEnum:
		return nil
	default:
		return fmt.Errorf("unsupported const type %s", typ.GoExpr)
	}
}

func (r *goRenderer) validateTypeUsage(typ *gomodel.Type, allowBinderObjects bool) error {
	if typ == nil {
		return fmt.Errorf("nil type")
	}
	switch typ.Kind {
	case gomodel.TypeVoid, gomodel.TypeBool, gomodel.TypeByte, gomodel.TypeChar, gomodel.TypeInt32, gomodel.TypeInt64, gomodel.TypeFloat32, gomodel.TypeFloat64, gomodel.TypeString, gomodel.TypeParcelable, gomodel.TypeEnum, gomodel.TypeUnion:
		return nil
	case gomodel.TypeFileDescriptor, gomodel.TypeParcelFileDescriptor:
		return nil
	case gomodel.TypeSlice, gomodel.TypeArray:
		return r.validateTypeUsage(typ.Elem, allowBinderObjects)
	case gomodel.TypeInterface, gomodel.TypeBinder:
		return nil
	case gomodel.TypeExternal:
		return fmt.Errorf("external type %q is not implemented yet", typ.AIDLName)
	default:
		return fmt.Errorf("unsupported type %q", typ.GoExpr)
	}
}

func (r *goRenderer) imports() []importSpec {
	set := map[string]importSpec{}
	add := func(path string, alias string) {
		key := alias + "\x00" + path
		set[key] = importSpec{Path: path, Alias: alias}
	}

	add(r.runtimeImportPath, "")
	if len(r.model.Interfaces) != 0 {
		add("context", "")
	}
	if len(r.model.Interfaces) != 0 || len(r.model.Unions) != 0 {
		add("fmt", "")
	}
	if r.hasStableInterfaces() {
		add("errors", "")
		add("sync", "")
	}
	for _, p := range r.model.Parcelables {
		if p.Custom == nil {
			continue
		}
		add(p.Custom.GoPackage, p.Custom.ImportAlias)
	}

	imports := make([]importSpec, 0, len(set))
	for _, imp := range set {
		imports = append(imports, imp)
	}
	sort.Slice(imports, func(i, j int) bool {
		if imports[i].Path == imports[j].Path {
			return imports[i].Alias < imports[j].Alias
		}
		return imports[i].Path < imports[j].Path
	})
	return imports
}

func (r *goRenderer) hasStableInterfaces() bool {
	for _, iface := range r.model.Interfaces {
		if iface.Stable {
			return true
		}
	}
	return false
}

func outputPath(model *gomodel.File) string {
	dir := "."
	if model.AIDLPackage != "" {
		dir = filepath.Join(strings.Split(model.AIDLPackage, ".")...)
	}
	base := "aidl_generated"
	if model.SourcePath != "" {
		base = strings.TrimSuffix(filepath.Base(model.SourcePath), filepath.Ext(model.SourcePath))
	}
	base = strings.ToLower(base) + "_aidl.go"
	return filepath.Join(dir, base)
}

func (r *goRenderer) renderEnum(enum *gomodel.Enum) {
	r.linef("type %s %s", enum.GoName, enum.Underlying.GoExpr)
	r.linef("")
	r.linef("const (")
	nextValue := int64(0)
	for i, member := range enum.Members {
		valueExpr := member.Value
		if valueExpr == "" {
			valueExpr = fmt.Sprintf("%d", nextValue)
		}
		r.linef("\t%s %s = %s", member.GoName, enum.GoName, valueExpr)
		if i == 0 && member.Value == "" {
			nextValue = 1
		} else if v, err := parseInt(member.Value); err == nil {
			nextValue = v + 1
		} else {
			nextValue++
		}
	}
	r.linef(")")
	r.linef("")
	r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", enum.GoName, enum.GoName)
	r.linef("\treturn %s", r.writeExpr("p", enumCastValue(enum), enumTypeAsBacking(enum), ""))
	r.linef("}")
	r.linef("")
	r.linef("func read%sFromParcel(p *binder.Parcel) (%s, error) {", enum.GoName, enum.GoName)
	r.linef("\tv, err := %s", r.readExpr("p", enumTypeAsBacking(enum)))
	r.linef("\tif err != nil {")
	r.linef("\t\treturn 0, err")
	r.linef("\t}")
	r.linef("\treturn %s(v), nil", enum.GoName)
	r.linef("}")
	r.linef("")
}

func enumTypeAsBacking(enum *gomodel.Enum) *gomodel.Type {
	return &gomodel.Type{
		Kind:      enum.Underlying.Kind,
		AIDLName:  enum.Underlying.AIDLName,
		GoExpr:    enum.Underlying.GoExpr,
		IsBuiltin: enum.Underlying.IsBuiltin,
	}
}

func enumCastValue(enum *gomodel.Enum) string {
	if enum == nil || enum.Underlying == nil {
		return "v"
	}
	return fmt.Sprintf("%s(v)", enum.Underlying.GoExpr)
}

func (r *goRenderer) renderParcelFileDescriptorHelpers() {
	r.linef("func writeNullableParcelFileDescriptorToParcel(p *binder.Parcel, v *binder.ParcelFileDescriptor) error {")
	r.linef("\tif v == nil {")
	r.linef("\t\treturn p.WriteParcelFileDescriptor(binder.NewParcelFileDescriptor(-1))")
	r.linef("\t}")
	r.linef("\treturn p.WriteParcelFileDescriptor(*v)")
	r.linef("}")
	r.linef("")
	r.linef("func readNullableParcelFileDescriptorFromParcel(p *binder.Parcel) (*binder.ParcelFileDescriptor, error) {")
	r.linef("\tv, err := p.ReadParcelFileDescriptor()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif v.FD() < 0 {")
	r.linef("\t\treturn nil, nil")
	r.linef("\t}")
	r.linef("\treturn &v, nil")
	r.linef("}")
	r.linef("")
	r.linef("func readRequiredParcelFileDescriptorFromParcel(p *binder.Parcel) (binder.ParcelFileDescriptor, error) {")
	r.linef("\tv, err := p.ReadParcelFileDescriptor()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn binder.ParcelFileDescriptor{}, err")
	r.linef("\t}")
	r.linef("\tif v.FD() < 0 {")
	r.linef("\t\treturn binder.ParcelFileDescriptor{}, binder.ErrBadParcelable")
	r.linef("\t}")
	r.linef("\treturn v, nil")
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderParcelable(p *gomodel.Parcelable) {
	if !p.Structured && p.Custom != nil {
		r.renderCustomParcelable(p)
		return
	}

	needsRegistrar := r.fieldsNeedRegistrar(p.Fields)

	r.linef("type %s struct {", p.GoName)
	for _, field := range p.Fields {
		r.linef("\t%s %s", field.GoName, field.Type.GoExpr)
	}
	r.linef("}")
	r.linef("")

	if needsRegistrar {
		r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", p.GoName, p.GoName)
		r.linef("\treturn write%sToParcelWithRegistrar(p, nil, v)", p.GoName)
		r.linef("}")
		r.linef("")
		r.linef("func write%sToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v %s) error {", p.GoName, p.GoName)
		for _, field := range p.Fields {
			r.linef("\tif err := %s; err != nil {", r.writeExpr("p", "v."+field.GoName, field.Type, "registrar"))
			r.linef("\t\treturn err")
			r.linef("\t}")
		}
		r.linef("\treturn nil")
		r.linef("}")
		r.linef("")
	} else {
		r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", p.GoName, p.GoName)
		for _, field := range p.Fields {
			r.linef("\tif err := %s; err != nil {", r.writeExpr("p", "v."+field.GoName, field.Type, ""))
			r.linef("\t\treturn err")
			r.linef("\t}")
		}
		r.linef("\treturn nil")
		r.linef("}")
		r.linef("")
	}

	r.linef("func read%sFromParcel(p *binder.Parcel) (%s, error) {", p.GoName, p.GoName)
	r.linef("\tvar v %s", p.GoName)
	for _, field := range p.Fields {
		r.linef("\t%sValue, err := %s", lowerFirst(field.GoName), r.readExpr("p", field.Type))
		r.linef("\tif err != nil {")
		r.linef("\t\treturn %s{}, err", p.GoName)
		r.linef("\t}")
		r.linef("\tv.%s = %sValue", field.GoName, lowerFirst(field.GoName))
	}
	r.linef("\treturn v, nil")
	r.linef("}")
	r.linef("")

	if needsRegistrar {
		r.linef("func writeNullable%sToParcel(p *binder.Parcel, v *%s) error {", p.GoName, p.GoName)
		r.linef("\treturn writeNullable%sToParcelWithRegistrar(p, nil, v)", p.GoName)
		r.linef("}")
		r.linef("")
		r.linef("func writeNullable%sToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v *%s) error {", p.GoName, p.GoName)
		r.linef("\tif v == nil {")
		r.linef("\t\treturn p.WriteInt32(0)")
		r.linef("\t}")
		r.linef("\tif err := p.WriteInt32(1); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\treturn write%sToParcelWithRegistrar(p, registrar, *v)", p.GoName)
		r.linef("}")
		r.linef("")
	} else {
		r.linef("func writeNullable%sToParcel(p *binder.Parcel, v *%s) error {", p.GoName, p.GoName)
		r.linef("\tif v == nil {")
		r.linef("\t\treturn p.WriteInt32(0)")
		r.linef("\t}")
		r.linef("\tif err := p.WriteInt32(1); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\treturn write%sToParcel(p, *v)", p.GoName)
		r.linef("}")
		r.linef("")
	}

	r.linef("func readNullable%sFromParcel(p *binder.Parcel) (*%s, error) {", p.GoName, p.GoName)
	r.linef("\tpresent, err := p.ReadInt32()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif present == 0 {")
	r.linef("\t\treturn nil, nil")
	r.linef("\t}")
	r.linef("\tv, err := read%sFromParcel(p)", p.GoName)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\treturn &v, nil")
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderCustomParcelable(p *gomodel.Parcelable) {
	custom := p.Custom
	goType := custom.ImportAlias + "." + custom.GoType

	r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", p.GoName, goType)
	r.linef("\treturn %s.%s(p, v)", custom.ImportAlias, custom.WriteFunc)
	r.linef("}")
	r.linef("")
	r.linef("func read%sFromParcel(p *binder.Parcel) (%s, error) {", p.GoName, goType)
	r.linef("\treturn %s.%s(p)", custom.ImportAlias, custom.ReadFunc)
	r.linef("}")
	r.linef("")
	r.linef("func writeNullable%sToParcel(p *binder.Parcel, v *%s) error {", p.GoName, goType)
	r.linef("\tif v == nil {")
	r.linef("\t\treturn p.WriteInt32(0)")
	r.linef("\t}")
	r.linef("\tif err := p.WriteInt32(1); err != nil {")
	r.linef("\t\treturn err")
	r.linef("\t}")
	r.linef("\treturn %s.%s(p, *v)", custom.ImportAlias, custom.WriteFunc)
	r.linef("}")
	r.linef("")
	r.linef("func readNullable%sFromParcel(p *binder.Parcel) (*%s, error) {", p.GoName, goType)
	r.linef("\tpresent, err := p.ReadInt32()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif present == 0 {")
	r.linef("\t\treturn nil, nil")
	r.linef("\t}")
	r.linef("\tv, err := %s.%s(p)", custom.ImportAlias, custom.ReadFunc)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\treturn &v, nil")
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderUnion(u *gomodel.Union) {
	needsRegistrar := r.fieldsNeedRegistrar(u.Fields)
	tagType := u.GoName + "Tag"

	r.linef("type %s int32", tagType)
	r.linef("")
	r.linef("const (")
	for i, field := range u.Fields {
		r.linef("\t%sTag%s %s = %d", u.GoName, field.GoName, tagType, i+1)
	}
	r.linef(")")
	r.linef("")

	r.linef("type %s struct {", u.GoName)
	r.linef("\tTag %s", tagType)
	for _, field := range u.Fields {
		r.linef("\t%s %s", field.GoName, field.Type.GoExpr)
	}
	r.linef("}")
	r.linef("")

	if needsRegistrar {
		r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", u.GoName, u.GoName)
		r.linef("\treturn write%sToParcelWithRegistrar(p, nil, v)", u.GoName)
		r.linef("}")
		r.linef("")
		r.linef("func write%sToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v %s) error {", u.GoName, u.GoName)
		r.linef("\tif err := p.WriteInt32(int32(v.Tag)); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\tswitch v.Tag {")
		for _, field := range u.Fields {
			r.linef("\tcase %sTag%s:", u.GoName, field.GoName)
			r.linef("\t\treturn %s", r.writeExpr("p", "v."+field.GoName, field.Type, "registrar"))
		}
		r.linef("\tdefault:")
		r.linef("\t\treturn fmt.Errorf(\"%%w: invalid %s tag %%d\", binder.ErrBadParcelable, v.Tag)", u.GoName)
		r.linef("\t}")
		r.linef("}")
		r.linef("")
	} else {
		r.linef("func write%sToParcel(p *binder.Parcel, v %s) error {", u.GoName, u.GoName)
		r.linef("\tif err := p.WriteInt32(int32(v.Tag)); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\tswitch v.Tag {")
		for _, field := range u.Fields {
			r.linef("\tcase %sTag%s:", u.GoName, field.GoName)
			r.linef("\t\treturn %s", r.writeExpr("p", "v."+field.GoName, field.Type, ""))
		}
		r.linef("\tdefault:")
		r.linef("\t\treturn fmt.Errorf(\"%%w: invalid %s tag %%d\", binder.ErrBadParcelable, v.Tag)", u.GoName)
		r.linef("\t}")
		r.linef("}")
		r.linef("")
	}

	r.linef("func read%sFromParcel(p *binder.Parcel) (%s, error) {", u.GoName, u.GoName)
	r.linef("\ttagValue, err := p.ReadInt32()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn %s{}, err", u.GoName)
	r.linef("\t}")
	r.linef("\tv := %s{Tag: %s(tagValue)}", u.GoName, tagType)
	r.linef("\tswitch v.Tag {")
	for _, field := range u.Fields {
		r.linef("\tcase %sTag%s:", u.GoName, field.GoName)
		r.linef("\t\tdecoded, err := %s", r.readExpr("p", field.Type))
		r.linef("\t\tif err != nil {")
		r.linef("\t\t\treturn %s{}, err", u.GoName)
		r.linef("\t\t}")
		r.linef("\t\tv.%s = decoded", field.GoName)
		r.linef("\t\treturn v, nil")
	}
	r.linef("\tdefault:")
	r.linef("\t\treturn %s{}, fmt.Errorf(\"%%w: invalid %s tag %%d\", binder.ErrBadParcelable, v.Tag)", u.GoName, u.GoName)
	r.linef("\t}")
	r.linef("}")
	r.linef("")

	if needsRegistrar {
		r.linef("func writeNullable%sToParcel(p *binder.Parcel, v *%s) error {", u.GoName, u.GoName)
		r.linef("\treturn writeNullable%sToParcelWithRegistrar(p, nil, v)", u.GoName)
		r.linef("}")
		r.linef("")
		r.linef("func writeNullable%sToParcelWithRegistrar(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v *%s) error {", u.GoName, u.GoName)
		r.linef("\tif v == nil {")
		r.linef("\t\treturn p.WriteInt32(0)")
		r.linef("\t}")
		r.linef("\tif err := p.WriteInt32(1); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\treturn write%sToParcelWithRegistrar(p, registrar, *v)", u.GoName)
		r.linef("}")
		r.linef("")
	} else {
		r.linef("func writeNullable%sToParcel(p *binder.Parcel, v *%s) error {", u.GoName, u.GoName)
		r.linef("\tif v == nil {")
		r.linef("\t\treturn p.WriteInt32(0)")
		r.linef("\t}")
		r.linef("\tif err := p.WriteInt32(1); err != nil {")
		r.linef("\t\treturn err")
		r.linef("\t}")
		r.linef("\treturn write%sToParcel(p, *v)", u.GoName)
		r.linef("}")
		r.linef("")
	}

	r.linef("func readNullable%sFromParcel(p *binder.Parcel) (*%s, error) {", u.GoName, u.GoName)
	r.linef("\tpresent, err := p.ReadInt32()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif present == 0 {")
	r.linef("\t\treturn nil, nil")
	r.linef("\t}")
	r.linef("\tv, err := read%sFromParcel(p)", u.GoName)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\treturn &v, nil")
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderInterface(iface *gomodel.Interface) {
	r.linef("const %sDescriptor = %q", iface.GoName, iface.Descriptor)
	if iface.Stable {
		r.linef("const %sInterfaceVersion int32 = %d", iface.GoName, iface.Version)
		r.linef("const %sInterfaceHash = %q", iface.GoName, iface.Hash)
	}
	for _, c := range iface.Consts {
		r.linef("const %s %s = %s", c.GoName, c.Type.GoExpr, c.Value)
	}
	for _, method := range iface.Methods {
		r.linef("const %sTransaction%s uint32 = %d", iface.GoName, method.GoName, method.TransactionCode)
	}
	r.linef("")

	r.linef("type %s interface {", iface.GoName)
	for _, method := range iface.Methods {
		r.linef("\t%s(%s) (%s)", method.GoName, r.methodInputs(method), r.methodReturns(method))
	}
	r.linef("}")
	r.linef("")

	clientType := lowerFirst(iface.GoName) + "Client"
	r.linef("type %s struct {", clientType)
	r.linef("\ttarget binder.Binder")
	if iface.Stable {
		r.linef("\tversionMu sync.Mutex")
		r.linef("\tversionResolved bool")
		r.linef("\tcachedVersion int32")
		r.linef("\thashMu sync.Mutex")
		r.linef("\thashResolved bool")
		r.linef("\tcachedHash string")
	}
	r.linef("}")
	r.linef("")
	r.linef("func New%sClient(target binder.Binder) %s {", iface.GoName, iface.GoName)
	r.linef("\tif target == nil {")
	r.linef("\t\treturn nil")
	r.linef("\t}")
	if iface.Stable {
		r.linef("\treturn &%s{target: target, cachedVersion: -1, cachedHash: \"-1\"}", clientType)
	} else {
		r.linef("\treturn &%s{target: target}", clientType)
	}
	r.linef("}")
	r.linef("")
	r.linef("func (c *%s) AsBinder() binder.Binder {", clientType)
	r.linef("\tif c == nil {")
	r.linef("\t\treturn nil")
	r.linef("\t}")
	r.linef("\treturn c.target")
	r.linef("}")
	r.linef("")
	if iface.Stable {
		r.renderStableInterfaceHelpers(iface, clientType)
	}
	r.linef("func write%sToParcel(p *binder.Parcel, registrar binder.LocalHandlerRegistrar, v %s) error {", iface.GoName, iface.GoName)
	r.linef("\tif v == nil {")
	r.linef("\t\treturn p.WriteStrongBinder(nil)")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(binder.BinderProvider); ok {")
	r.linef("\t\treturn p.WriteStrongBinder(provider.AsBinder())")
	r.linef("\t}")
	r.linef("\tif registrar == nil {")
	r.linef("\t\treturn fmt.Errorf(\"%%w: no local handler registrar available for %s\", binder.ErrUnsupported)", iface.GoName)
	r.linef("\t}")
	r.linef("\tb, err := registrar.RegisterLocalHandler(New%sHandlerWithRegistrar(registrar, v))", iface.GoName)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn err")
	r.linef("\t}")
	r.linef("\treturn p.WriteStrongBinder(b)")
	r.linef("}")
	r.linef("")
	r.linef("func read%sFromParcel(p *binder.Parcel) (%s, error) {", iface.GoName, iface.GoName)
	r.linef("\tb, err := p.ReadStrongBinder()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif b == nil {")
	r.linef("\t\treturn nil, nil")
	r.linef("\t}")
	r.linef("\treturn New%sClient(b), nil", iface.GoName)
	r.linef("}")
	r.linef("")

	for _, method := range iface.Methods {
		r.renderProxyMethod(iface, clientType, method)
	}

	handlerType := lowerFirst(iface.GoName) + "Handler"
	r.linef("type %s struct {", handlerType)
	r.linef("\timpl %s", iface.GoName)
	r.linef("\tregistrar binder.LocalHandlerRegistrar")
	r.linef("}")
	r.linef("")
	r.linef("func New%sHandler(impl %s) binder.Handler {", iface.GoName, iface.GoName)
	r.linef("\treturn New%sHandlerWithRegistrar(nil, impl)", iface.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func New%sHandlerWithRegistrar(registrar binder.LocalHandlerRegistrar, impl %s) binder.Handler {", iface.GoName, iface.GoName)
	r.linef("\treturn &%s{impl: impl, registrar: registrar}", handlerType)
	r.linef("}")
	r.linef("")
	r.linef("func (h *%s) Descriptor() string {", handlerType)
	r.linef("\treturn %sDescriptor", iface.GoName)
	r.linef("}")
	r.linef("")
	if iface.Stable {
		r.linef("func (h *%s) InterfaceVersion() int32 {", handlerType)
		r.linef("\treturn %sInterfaceVersion", iface.GoName)
		r.linef("}")
		r.linef("")
		r.linef("func (h *%s) InterfaceHash() string {", handlerType)
		r.linef("\treturn %sInterfaceHash", iface.GoName)
		r.linef("}")
		r.linef("")
	}
	r.linef("func (h *%s) HandleTransact(ctx context.Context, code uint32, data *binder.Parcel) (*binder.Parcel, error) {", handlerType)
	r.linef("\tdescriptor, err := data.ReadInterfaceToken()")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\tif descriptor != %sDescriptor {", iface.GoName)
	r.linef("\t\treturn nil, fmt.Errorf(\"%%w: descriptor %%q, want %%q\", binder.ErrBadParcelable, descriptor, %sDescriptor)", iface.GoName)
	r.linef("\t}")
	r.linef("\tswitch code {")
	for _, method := range iface.Methods {
		r.renderHandlerCase(iface, method)
	}
	r.linef("\tdefault:")
	r.linef("\t\treturn nil, fmt.Errorf(\"%%w: %s transaction code %%d\", binder.ErrUnknownTransaction, code)", iface.GoName)
	r.linef("\t}")
	r.linef("}")
	r.linef("")

	r.linef("func Check%sService(ctx context.Context, sm binder.ServiceManager, name string) (%s, error) {", iface.GoName, iface.GoName)
	r.linef("\tservice, err := sm.CheckService(ctx, name)")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\treturn New%sClient(service), nil", iface.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func Wait%sService(ctx context.Context, sm binder.ServiceManager, name string) (%s, error) {", iface.GoName, iface.GoName)
	r.linef("\tservice, err := sm.WaitService(ctx, name)")
	r.linef("\tif err != nil {")
	r.linef("\t\treturn nil, err")
	r.linef("\t}")
	r.linef("\treturn New%sClient(service), nil", iface.GoName)
	r.linef("}")
	r.linef("")
	r.linef("func Add%sService(ctx context.Context, sm binder.ServiceManager, name string, impl %s, opts ...binder.AddServiceOption) error {", iface.GoName, iface.GoName)
	r.linef("\tif registrar, ok := sm.(binder.LocalHandlerRegistrar); ok {")
	r.linef("\t\treturn sm.AddService(ctx, name, New%sHandlerWithRegistrar(registrar, impl), opts...)", iface.GoName)
	r.linef("\t}")
	r.linef("\treturn sm.AddService(ctx, name, New%sHandler(impl), opts...)", iface.GoName)
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderStableInterfaceHelpers(iface *gomodel.Interface, clientType string) {
	r.linef("func query%sInterfaceVersion(ctx context.Context, target binder.Binder) (int32, error) {", iface.GoName)
	r.linef("\tversion, err := binder.GetInterfaceVersion(ctx, target)")
	r.linef("\tif err != nil {")
	r.linef("\t\tif errors.Is(err, binder.ErrUnknownTransaction) {")
	r.linef("\t\t\treturn -1, nil")
	r.linef("\t\t}")
	r.linef("\t\treturn -1, err")
	r.linef("\t}")
	r.linef("\treturn version, nil")
	r.linef("}")
	r.linef("")
	r.linef("func query%sInterfaceHash(ctx context.Context, target binder.Binder) (string, error) {", iface.GoName)
	r.linef("\thash, err := binder.GetInterfaceHash(ctx, target)")
	r.linef("\tif err != nil {")
	r.linef("\t\tif errors.Is(err, binder.ErrUnknownTransaction) {")
	r.linef("\t\t\treturn \"-1\", nil")
	r.linef("\t\t}")
	r.linef("\t\treturn \"\", err")
	r.linef("\t}")
	r.linef("\treturn hash, nil")
	r.linef("}")
	r.linef("")
	r.linef("func (c *%s) InterfaceVersion(ctx context.Context) (int32, error) {", clientType)
	r.linef("\tif c == nil || c.target == nil {")
	r.linef("\t\treturn -1, binder.ErrUnsupported")
	r.linef("\t}")
	r.linef("\tc.versionMu.Lock()")
	r.linef("\tdefer c.versionMu.Unlock()")
	r.linef("\tif c.versionResolved {")
	r.linef("\t\treturn c.cachedVersion, nil")
	r.linef("\t}")
	r.linef("\tversion, err := query%sInterfaceVersion(ctx, c.target)", iface.GoName)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn -1, err")
	r.linef("\t}")
	r.linef("\tc.cachedVersion = version")
	r.linef("\tc.versionResolved = true")
	r.linef("\treturn version, nil")
	r.linef("}")
	r.linef("")
	r.linef("func (c *%s) InterfaceHash(ctx context.Context) (string, error) {", clientType)
	r.linef("\tif c == nil || c.target == nil {")
	r.linef("\t\treturn \"\", binder.ErrUnsupported")
	r.linef("\t}")
	r.linef("\tc.hashMu.Lock()")
	r.linef("\tdefer c.hashMu.Unlock()")
	r.linef("\tif c.hashResolved {")
	r.linef("\t\treturn c.cachedHash, nil")
	r.linef("\t}")
	r.linef("\thash, err := query%sInterfaceHash(ctx, c.target)", iface.GoName)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn \"\", err")
	r.linef("\t}")
	r.linef("\tc.cachedHash = hash")
	r.linef("\tc.hashResolved = true")
	r.linef("\treturn hash, nil")
	r.linef("}")
	r.linef("")
	r.linef("func Get%sInterfaceVersion(ctx context.Context, v %s) (int32, error) {", iface.GoName, iface.GoName)
	r.linef("\tif v == nil {")
	r.linef("\t\treturn -1, binder.ErrUnsupported")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(interface {")
	r.linef("\t\tInterfaceVersion(context.Context) (int32, error)")
	r.linef("\t}); ok {")
	r.linef("\t\treturn provider.InterfaceVersion(ctx)")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(binder.InterfaceVersionProvider); ok {")
	r.linef("\t\treturn provider.InterfaceVersion(), nil")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(binder.BinderProvider); ok {")
	r.linef("\t\treturn query%sInterfaceVersion(ctx, provider.AsBinder())", iface.GoName)
	r.linef("\t}")
	r.linef("\treturn -1, binder.ErrUnsupported")
	r.linef("}")
	r.linef("")
	r.linef("func Get%sInterfaceHash(ctx context.Context, v %s) (string, error) {", iface.GoName, iface.GoName)
	r.linef("\tif v == nil {")
	r.linef("\t\treturn \"\", binder.ErrUnsupported")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(interface {")
	r.linef("\t\tInterfaceHash(context.Context) (string, error)")
	r.linef("\t}); ok {")
	r.linef("\t\treturn provider.InterfaceHash(ctx)")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(binder.InterfaceHashProvider); ok {")
	r.linef("\t\treturn provider.InterfaceHash(), nil")
	r.linef("\t}")
	r.linef("\tif provider, ok := any(v).(binder.BinderProvider); ok {")
	r.linef("\t\treturn query%sInterfaceHash(ctx, provider.AsBinder())", iface.GoName)
	r.linef("\t}")
	r.linef("\treturn \"\", binder.ErrUnsupported")
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderProxyMethod(iface *gomodel.Interface, clientType string, method *gomodel.Method) {
	r.linef("func (c *%s) %s(%s) (%s) {", clientType, method.GoName, r.methodInputs(method), r.methodReturns(method))
	r.linef("\tif ctx == nil {")
	r.linef("\t\tctx = context.Background()")
	r.linef("\t}")
	r.linef("\tdata := binder.NewParcel()")
	r.linef("\tif err := data.WriteInterfaceToken(%sDescriptor); err != nil {", iface.GoName)
	r.linef("\t\treturn %s", r.methodErrorReturn(method, "err"))
	r.linef("\t}")
	if r.methodNeedsRegistrar(method.Inputs) {
		r.linef("\tvar registrar binder.LocalHandlerRegistrar")
		r.linef("\tif resolved, ok := c.target.(binder.LocalHandlerRegistrar); ok {")
		r.linef("\t\tregistrar = resolved")
		r.linef("\t}")
	}
	for _, arg := range method.Inputs {
		r.linef("\tif err := %s; err != nil {", r.writeExpr("data", arg.GoName, arg.Type, "registrar"))
		r.linef("\t\treturn %s", r.methodErrorReturn(method, "err"))
		r.linef("\t}")
	}
	flagExpr := "binder.FlagNone"
	if method.Oneway {
		flagExpr = "binder.FlagOneway"
	}
	r.linef("\treply, err := c.target.Transact(ctx, %sTransaction%s, data, %s)", iface.GoName, method.GoName, flagExpr)
	r.linef("\tif err != nil {")
	r.linef("\t\treturn %s", r.methodErrorReturn(method, "err"))
	r.linef("\t}")
	if method.Oneway {
		r.linef("\treturn nil")
		r.linef("}")
		r.linef("")
		return
	}
	r.linef("\tif reply == nil {")
	r.linef("\t\treturn %s", r.methodErrorReturn(method, "binder.ErrBadParcelable"))
	r.linef("\t}")
	if method.Return != nil {
		r.linef("\tret, err := %s", r.readExpr("reply", method.Return.Type))
		r.linef("\tif err != nil {")
		r.linef("\t\treturn %s", r.methodErrorReturn(method, "err"))
		r.linef("\t}")
	}
	for _, out := range method.Outputs {
		r.linef("\t%s, err := %s", out.GoName, r.readExpr("reply", out.Type))
		r.linef("\tif err != nil {")
		r.linef("\t\treturn %s", r.methodErrorReturn(method, "err"))
		r.linef("\t}")
	}
	r.linef("\treturn %s", r.methodSuccessReturn(method))
	r.linef("}")
	r.linef("")
}

func (r *goRenderer) renderHandlerCase(iface *gomodel.Interface, method *gomodel.Method) {
	r.linef("\tcase %sTransaction%s:", iface.GoName, method.GoName)
	for _, arg := range method.Inputs {
		r.linef("\t\t%s, err := %s", arg.GoName, r.readExpr("data", arg.Type))
		r.linef("\t\tif err != nil {")
		r.linef("\t\t\treturn nil, err")
		r.linef("\t\t}")
	}
	callArgs := make([]string, 0, 1+len(method.Inputs))
	callArgs = append(callArgs, "ctx")
	for _, arg := range method.Inputs {
		callArgs = append(callArgs, arg.GoName)
	}
	if method.Oneway {
		r.linef("\t\treturn nil, h.impl.%s(%s)", method.GoName, strings.Join(callArgs, ", "))
		return
	}

	resultVars := make([]string, 0, len(method.Outputs)+2)
	if method.Return != nil {
		resultVars = append(resultVars, "ret")
	}
	for _, out := range method.Outputs {
		resultVars = append(resultVars, out.GoName)
	}
	resultVars = append(resultVars, "err")
	r.linef("\t\t%s := h.impl.%s(%s)", strings.Join(resultVars, ", "), method.GoName, strings.Join(callArgs, ", "))
	r.linef("\t\tif err != nil {")
	r.linef("\t\t\treturn nil, err")
	r.linef("\t\t}")
	r.linef("\t\treply := binder.NewParcel()")
	if method.Return != nil {
		r.linef("\t\tif err := %s; err != nil {", r.writeExpr("reply", "ret", method.Return.Type, "h.registrar"))
		r.linef("\t\t\treturn nil, err")
		r.linef("\t\t}")
	}
	for _, out := range method.Outputs {
		r.linef("\t\tif err := %s; err != nil {", r.writeExpr("reply", out.GoName, out.Type, "h.registrar"))
		r.linef("\t\t\treturn nil, err")
		r.linef("\t\t}")
	}
	r.linef("\t\treturn reply, nil")
}

func (r *goRenderer) methodInputs(method *gomodel.Method) string {
	parts := []string{"ctx context.Context"}
	for _, arg := range method.Inputs {
		parts = append(parts, fmt.Sprintf("%s %s", arg.GoName, arg.Type.GoExpr))
	}
	return strings.Join(parts, ", ")
}

func (r *goRenderer) methodReturns(method *gomodel.Method) string {
	if method.Oneway {
		return "error"
	}
	var parts []string
	if method.Return != nil {
		parts = append(parts, method.Return.Type.GoExpr)
	}
	for _, out := range method.Outputs {
		parts = append(parts, out.Type.GoExpr)
	}
	parts = append(parts, "error")
	return strings.Join(parts, ", ")
}

func (r *goRenderer) methodErrorReturn(method *gomodel.Method, errExpr string) string {
	if method.Oneway {
		return errExpr
	}
	var parts []string
	if method.Return != nil {
		parts = append(parts, zeroExpr(method.Return.Type))
	}
	for _, out := range method.Outputs {
		parts = append(parts, zeroExpr(out.Type))
	}
	parts = append(parts, errExpr)
	return strings.Join(parts, ", ")
}

func (r *goRenderer) methodSuccessReturn(method *gomodel.Method) string {
	if method.Oneway {
		return "nil"
	}
	var parts []string
	if method.Return != nil {
		parts = append(parts, "ret")
	}
	for _, out := range method.Outputs {
		parts = append(parts, out.GoName)
	}
	parts = append(parts, "nil")
	return strings.Join(parts, ", ")
}

func (r *goRenderer) writeExpr(parcel string, value string, typ *gomodel.Type, registrar string) string {
	switch typ.Kind {
	case gomodel.TypeBool:
		return fmt.Sprintf("%s.WriteBool(%s)", parcel, value)
	case gomodel.TypeByte:
		return fmt.Sprintf("%s.WriteByte(%s)", parcel, value)
	case gomodel.TypeChar:
		return fmt.Sprintf("%s.WriteChar(%s)", parcel, value)
	case gomodel.TypeInt32:
		return fmt.Sprintf("%s.WriteInt32(%s)", parcel, value)
	case gomodel.TypeInt64:
		return fmt.Sprintf("%s.WriteInt64(%s)", parcel, value)
	case gomodel.TypeFloat32:
		return fmt.Sprintf("%s.WriteFloat32(%s)", parcel, value)
	case gomodel.TypeFloat64:
		return fmt.Sprintf("%s.WriteFloat64(%s)", parcel, value)
	case gomodel.TypeString:
		if typ.Nullable {
			return fmt.Sprintf("%s.WriteNullableString(%s)", parcel, value)
		}
		return fmt.Sprintf("%s.WriteString(%s)", parcel, value)
	case gomodel.TypeParcelable:
		if r.typeNeedsRegistrar(typ) {
			if typ.Nullable {
				return fmt.Sprintf("writeNullable%sToParcelWithRegistrar(%s, %s, %s)", typ.NamedGo, parcel, registrarExpr(registrar), value)
			}
			return fmt.Sprintf("write%sToParcelWithRegistrar(%s, %s, %s)", typ.NamedGo, parcel, registrarExpr(registrar), value)
		}
		if typ.Nullable {
			return fmt.Sprintf("writeNullable%sToParcel(%s, %s)", typ.NamedGo, parcel, value)
		}
		return fmt.Sprintf("write%sToParcel(%s, %s)", typ.NamedGo, parcel, value)
	case gomodel.TypeEnum:
		return fmt.Sprintf("write%sToParcel(%s, %s)", typ.NamedGo, parcel, value)
	case gomodel.TypeUnion:
		if r.typeNeedsRegistrar(typ) {
			if typ.Nullable {
				return fmt.Sprintf("writeNullable%sToParcelWithRegistrar(%s, %s, %s)", typ.NamedGo, parcel, registrarExpr(registrar), value)
			}
			return fmt.Sprintf("write%sToParcelWithRegistrar(%s, %s, %s)", typ.NamedGo, parcel, registrarExpr(registrar), value)
		}
		if typ.Nullable {
			return fmt.Sprintf("writeNullable%sToParcel(%s, %s)", typ.NamedGo, parcel, value)
		}
		return fmt.Sprintf("write%sToParcel(%s, %s)", typ.NamedGo, parcel, value)
	case gomodel.TypeBinder:
		return fmt.Sprintf("%s.WriteStrongBinder(%s)", parcel, value)
	case gomodel.TypeFileDescriptor:
		return fmt.Sprintf("%s.WriteFileDescriptor(%s)", parcel, value)
	case gomodel.TypeParcelFileDescriptor:
		if typ.Nullable {
			return fmt.Sprintf("writeNullableParcelFileDescriptorToParcel(%s, %s)", parcel, value)
		}
		return fmt.Sprintf("%s.WriteParcelFileDescriptor(%s)", parcel, value)
	case gomodel.TypeInterface:
		return fmt.Sprintf("write%sToParcel(%s, %s, %s)", typ.NamedGo, parcel, registrarExpr(registrar), value)
	case gomodel.TypeSlice:
		return fmt.Sprintf("binder.WriteSlice(%s, %s, func(p *binder.Parcel, item %s) error { return %s })", parcel, value, typ.Elem.GoExpr, r.writeExpr("p", "item", typ.Elem, registrar))
	case gomodel.TypeArray:
		return fmt.Sprintf("binder.WriteFixedSlice(%s, %s[:], %d, func(p *binder.Parcel, item %s) error { return %s })", parcel, value, typ.FixedLen, typ.Elem.GoExpr, r.writeExpr("p", "item", typ.Elem, registrar))
	default:
		return fmt.Sprintf("fmt.Errorf(\"%%w: unsupported type %s\", binder.ErrUnsupported)", typ.GoExpr)
	}
}

func (r *goRenderer) readExpr(parcel string, typ *gomodel.Type) string {
	switch typ.Kind {
	case gomodel.TypeBool:
		return fmt.Sprintf("%s.ReadBool()", parcel)
	case gomodel.TypeByte:
		return fmt.Sprintf("%s.ReadByte()", parcel)
	case gomodel.TypeChar:
		return fmt.Sprintf("%s.ReadChar()", parcel)
	case gomodel.TypeInt32:
		return fmt.Sprintf("%s.ReadInt32()", parcel)
	case gomodel.TypeInt64:
		return fmt.Sprintf("%s.ReadInt64()", parcel)
	case gomodel.TypeFloat32:
		return fmt.Sprintf("%s.ReadFloat32()", parcel)
	case gomodel.TypeFloat64:
		return fmt.Sprintf("%s.ReadFloat64()", parcel)
	case gomodel.TypeString:
		if typ.Nullable {
			return fmt.Sprintf("%s.ReadNullableString()", parcel)
		}
		return fmt.Sprintf("%s.ReadString()", parcel)
	case gomodel.TypeParcelable:
		if typ.Nullable {
			return fmt.Sprintf("readNullable%sFromParcel(%s)", typ.NamedGo, parcel)
		}
		return fmt.Sprintf("read%sFromParcel(%s)", typ.NamedGo, parcel)
	case gomodel.TypeEnum:
		return fmt.Sprintf("read%sFromParcel(%s)", typ.NamedGo, parcel)
	case gomodel.TypeUnion:
		if typ.Nullable {
			return fmt.Sprintf("readNullable%sFromParcel(%s)", typ.NamedGo, parcel)
		}
		return fmt.Sprintf("read%sFromParcel(%s)", typ.NamedGo, parcel)
	case gomodel.TypeBinder:
		return fmt.Sprintf("%s.ReadStrongBinder()", parcel)
	case gomodel.TypeFileDescriptor:
		return fmt.Sprintf("%s.ReadFileDescriptor()", parcel)
	case gomodel.TypeParcelFileDescriptor:
		if typ.Nullable {
			return fmt.Sprintf("readNullableParcelFileDescriptorFromParcel(%s)", parcel)
		}
		return fmt.Sprintf("readRequiredParcelFileDescriptorFromParcel(%s)", parcel)
	case gomodel.TypeInterface:
		return fmt.Sprintf("read%sFromParcel(%s)", typ.NamedGo, parcel)
	case gomodel.TypeSlice:
		return fmt.Sprintf("binder.ReadSlice(%s, func(p *binder.Parcel) (%s, error) { return %s })", parcel, typ.Elem.GoExpr, r.readExpr("p", typ.Elem))
	case gomodel.TypeArray:
		return fmt.Sprintf(`func() (%s, error) {
	items, err := binder.ReadFixedSlice(%s, %d, func(p *binder.Parcel) (%s, error) { return %s })
	if err != nil {
		return %s, err
	}
	var value %s
	copy(value[:], items)
	return value, nil
}()`, typ.GoExpr, parcel, typ.FixedLen, typ.Elem.GoExpr, r.readExpr("p", typ.Elem), zeroExpr(typ), typ.GoExpr)
	default:
		return fmt.Sprintf("func() (%s, error) { return %s, fmt.Errorf(\"%%w: unsupported type %s\", binder.ErrUnsupported) }()", typ.GoExpr, zeroExpr(typ), typ.GoExpr)
	}
}

func zeroExpr(typ *gomodel.Type) string {
	if typ == nil {
		return "nil"
	}
	switch typ.Kind {
	case gomodel.TypeBool:
		return "false"
	case gomodel.TypeByte, gomodel.TypeChar, gomodel.TypeInt32, gomodel.TypeInt64, gomodel.TypeFloat32, gomodel.TypeFloat64, gomodel.TypeEnum:
		return fmt.Sprintf("%s(0)", typ.GoExpr)
	case gomodel.TypeString:
		if typ.Nullable {
			return "nil"
		}
		return `""`
	case gomodel.TypeFileDescriptor:
		return "binder.FileDescriptor{}"
	case gomodel.TypeParcelFileDescriptor:
		if typ.Nullable {
			return "nil"
		}
		return "binder.ParcelFileDescriptor{}"
	case gomodel.TypeParcelable, gomodel.TypeUnion, gomodel.TypeArray:
		if typ.Nullable {
			return "nil"
		}
		return "*new(" + typ.GoExpr + ")"
	case gomodel.TypeSlice:
		return "nil"
	case gomodel.TypeInterface, gomodel.TypeBinder:
		return "nil"
	default:
		if typ.Nullable {
			return "nil"
		}
		if typ.GoExpr == "" {
			return "nil"
		}
		return typ.GoExpr + "{}"
	}
}

func parseInt(value string) (int64, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return 0, fmt.Errorf("empty")
	}
	var sign int64 = 1
	if strings.HasPrefix(value, "-") {
		sign = -1
		value = strings.TrimPrefix(value, "-")
	}
	var n int64
	for _, r := range value {
		if r < '0' || r > '9' {
			return 0, fmt.Errorf("not decimal")
		}
		n = n*10 + int64(r-'0')
	}
	return sign * n, nil
}

func lowerFirst(name string) string {
	if name == "" {
		return ""
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func registrarExpr(name string) string {
	if name == "" {
		return "nil"
	}
	return name
}

func (r *goRenderer) methodNeedsRegistrar(fields []gomodel.Field) bool {
	return r.fieldsNeedRegistrar(fields)
}

func (r *goRenderer) fieldsNeedRegistrar(fields []gomodel.Field) bool {
	for _, field := range fields {
		if r.typeNeedsRegistrar(field.Type) {
			return true
		}
	}
	return false
}

func (r *goRenderer) typeNeedsRegistrar(typ *gomodel.Type) bool {
	return r.typeNeedsRegistrarSeen(typ, map[string]struct{}{})
}

func (r *goRenderer) typeNeedsRegistrarSeen(typ *gomodel.Type, seen map[string]struct{}) bool {
	if typ == nil {
		return false
	}
	switch typ.Kind {
	case gomodel.TypeInterface:
		return true
	case gomodel.TypeSlice, gomodel.TypeArray:
		return r.typeNeedsRegistrarSeen(typ.Elem, seen)
	case gomodel.TypeParcelable:
		if typ.NamedGo == "" {
			return false
		}
		key := "parcelable:" + typ.NamedGo
		if _, ok := seen[key]; ok {
			return false
		}
		seen[key] = struct{}{}
		defer delete(seen, key)
		p := r.parcelablesByName[typ.NamedGo]
		if p == nil {
			return false
		}
		return r.fieldsNeedRegistrarSeen(p.Fields, seen)
	case gomodel.TypeUnion:
		if typ.NamedGo == "" {
			return false
		}
		key := "union:" + typ.NamedGo
		if _, ok := seen[key]; ok {
			return false
		}
		seen[key] = struct{}{}
		defer delete(seen, key)
		u := r.unionsByName[typ.NamedGo]
		if u == nil {
			return false
		}
		return r.fieldsNeedRegistrarSeen(u.Fields, seen)
	default:
		return false
	}
}

func (r *goRenderer) fieldsNeedRegistrarSeen(fields []gomodel.Field, seen map[string]struct{}) bool {
	for _, field := range fields {
		if r.typeNeedsRegistrarSeen(field.Type, seen) {
			return true
		}
	}
	return false
}

func (r *goRenderer) linef(format string, args ...any) {
	if len(args) == 0 {
		r.buf.WriteString(format)
		r.buf.WriteByte('\n')
		return
	}
	fmt.Fprintf(&r.buf, format+"\n", args...)
}
